version: "3.7"

volumes:
  db:
  oradata:

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rolldebee
      POSTGRES_PASSWORD: rolldebee
    volumes:
      - db:/var/lib/postgresql/data
  oracle:
    image: container-registry.oracle.com/database/free:23.5.0.0
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle
    volumes:
      - oradata:/opt/oracle/oradata
      - ./sql/oracle:/opt/oracle/scripts/startup
  api:
    image: rolldebee/api
    build:
      context: ./api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rolldebee
      - SPRING_DATASOURCE_USERNAME=rolldebee
      - SPRING_DATASOURCE_PASSWORD=rolldebee
      - ORACLE_HOST=oracle
    restart: on-failure
  ui:
    image: rolldebee/ui
    build:
      context: ./ui
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://127.0.0.1:8080
    restart: on-failure
