version: '3.8'

volumes:
  postgres:
    name: rolldebee-postgres
  oradata:
    name: oradata

services:
  postgres:
    container_name: rolldebee-postgres
    image: postgres:15.1
    ports:
      - ${ROLLDEBEE_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: rolldebee
      POSTGRES_PASSWORD: rolldebee
    volumes:
      - postgres:/var/lib/postgresql/data
  oracle:
    container_name: oracle
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - ${ROLLDEBEE_ORACLE_PORT}:1521
    environment:
      - ORACLE_PWD=oracle
    volumes:
      - oradata:/opt/oracle/oradata
      - ./infra/oracle:/opt/oracle/scripts/startup
  adminer:
    container_name: rolldebee-adminer
    image: adminer:4.8.1
    ports:
      - ${ROLLDEBEE_ADMINER_PORT}:8080
  api:
    container_name: rolldebee-api
    image: rolldebee/api
    build:
      context: ./api
    depends_on:
      - postgres
      - oracle
    ports:
      - ${ROLLDEBEE_API_PORT}:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rolldebee
      - SPRING_DATASOURCE_USERNAME=rolldebee
      - SPRING_DATASOURCE_PASSWORD=rolldebee
      - ORACLE_HOST=oracle
    restart: on-failure
  ui:
    container_name: rolldebee-ui
    image: rolldebee/ui
    build:
      context: ./ui
    depends_on:
      - api
    ports:
      - ${ROLLDEBEE_UI_PORT}:3000
    environment:
      - API_URL=http://api:${ROLLDEBEE_API_PORT}
    restart: on-failure
