ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER SCHEMA2 IDENTIFIED BY "schema2";

GRANT CONNECT, RESOURCE, CREATE TABLE, DBA TO SCHEMA2;

GRANT CREATE SESSION TO SCHEMA2;

ALTER SESSION SET CURRENT_SCHEMA="SCHEMA2";

CREATE TABLE DAYNE_OF_STARFALL (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  TOBBOT CLOB,
  DRYN DATE,
  VICTOR_TYRELL NUMERIC,
  ROSLIN_FREY VARCHAR2(465),
  NORREN VARCHAR2(3963),
  JORAH_MORMONT NUMERIC,
  BORCAS FLOAT,
  MARYA_SEAWORTH INTEGER,
  GARRETT_PAEGE CLOB,
  VAEMOND_VELARYON NUMBER,
  MEIZO_MAHR VARCHAR2(3963),
  DAGON_GREYJOY VARCHAR2(2290),
  STEFFON_BARATHEON VARCHAR2(3963),
  ARRYK SMALLINT,
  DAVEN_LANNISTER VARCHAR2(3963),
  TRISTIFER_BOTLEY DECIMAL,
  GYLBERT_FARWYND CLOB,
  NYMERIA VARCHAR2(2290),
  DAMON_SHETT SMALLINT,
  AEMON_BLACKFYRE FLOAT,
  TRISTON_FARWYND DATE,
  EDRIC_DAYNE VARCHAR2(2290),
  ROBERT_ARRYN FLOAT,
  ANDREY_CHARLTON DECIMAL,
  WALDER_VANCE FLOAT,
  JHEZANE TIMESTAMP,
  MUSHROOM VARCHAR2(465),
  EON_HUNTER INTEGER,
  TOMMEN_COSTAYNE SMALLINT,
  SHIERLE_SWYFT VARCHAR2(873),
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  CRESSEY_ID VARCHAR2(36),
  PECKLEDON_ID VARCHAR2(36),
  GREYIRON_OF_ORKMONT_ID VARCHAR2(36)
);

CREATE TABLE GAUNT (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  ADDAM_OSGREY VARCHAR2(2290),
  WARRYN_BEESBURY CLOB,
  JONNEL_STARK SMALLINT,
  XHONDO NUMERIC,
  ALESTER_FLORENT VARCHAR2(3963),
  DAVOS_SEAWORTH VARCHAR2(2622),
  LIKELY_LUKE TIMESTAMP,
  TERRO SMALLINT,
  MEZZARA NUMERIC,
  SHERRIT SMALLINT,
  RAYMUN_DARRY VARCHAR2(3963),
  OTTYN_WYTHERS VARCHAR2(2622),
  ORMOND FLOAT,
  DICK VARCHAR2(2622),
  ALESANDER_STAEDMON DATE,
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  PECKLEDON_ID VARCHAR2(36),
  GREYIRON_OF_ORKMONT_ID VARCHAR2(36)
);

CREATE TABLE PECKLEDON (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  MOTHER_MOLE VARCHAR2(2622),
  HARLON_GREYJOY INTEGER,
  CEDRIK_STORM DECIMAL,
  RAYNARD VARCHAR2(3963),
  ANDRIK CLOB,
  MORREC VARCHAR2(465),
  ALYN_FREY VARCHAR2(3963),
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  CRESSEY_ID VARCHAR2(36)
);

CREATE TABLE GREYIRON_OF_ORKMONT (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  ROBIN_FLINT VARCHAR2(2622),
  EBROSE NUMERIC,
  EBBEN DECIMAL,
  WALDER_FREY TIMESTAMP,
  WALDA_FREY INTEGER,
  DONAL_NOYE NUMERIC,
  JAYNE_BRACKEN VARCHAR2(873),
  HIGH_SPARROW FLOAT,
  TRISTON_OF_TALLY_HILL VARCHAR2(2622),
  ORMUND_WYLDE TIMESTAMP,
  AERYS_I_TARGARYEN SMALLINT,
  GRAZDAN INTEGER,
  MANFRED_DONDARRION INTEGER,
  ALLISER_THORNE VARCHAR2(2622),
  AEGON_TARGARYEN VARCHAR2(873),
  ERRYK CLOB,
  RYGER_RIVERS TIMESTAMP,
  GYLORO_DOTHARE VARCHAR2(873),
  HERBERT_BOLLING NUMERIC,
  GLENDON_HEWETT VARCHAR2(465),
  JEYNE_SWANN VARCHAR2(2622),
  NAERYS_TARGARYEN VARCHAR2(2290),
  MAELOR_TARGARYEN VARCHAR2(2290),
  HAEGON_BLACKFYRE FLOAT,
  CUGER NUMBER,
  SHIERA_SEASTAR DECIMAL,
  BELIS VARCHAR2(2290),
  LORREN DATE,
  SYLWA_PAEGE DECIMAL,
  BENEDICT_BROOM VARCHAR2(2622),
  LENNOCKS NUMERIC,
  GERRICK_KINGSBLOOD DECIMAL,
  GARTH_TYRELL DECIMAL,
  STONESNAKE NUMERIC,
  DONNOR_STARK VARCHAR2(2622),
  ALYN_VELARYON VARCHAR2(2290),
  SYMOND_FREY DECIMAL,
  EDWYN_OSGREY FLOAT,
  RHAENA_TARGARYEN TIMESTAMP,
  TIM_TANGLETONGUE INTEGER,
  QYLE SMALLINT,
  MYA_STONE NUMBER,
  URRON_GREYIRON VARCHAR2(873),
  BETHANY_BOLTON VARCHAR2(465),
  AEMON_COSTAYNE NUMERIC,
  KYLEG_OF_THE_WOODEN_EAR INTEGER,
  MORTON_WAYNWOOD VARCHAR2(2290),
  TORWYND NUMERIC,
  LORD_CAFFEREN VARCHAR2(2622),
  JON_PENNY FLOAT,
  EZZARA VARCHAR2(3963),
  LARK DECIMAL,
  ALYSANNE_BULWER VARCHAR2(2622),
  HOSMAN_NORCROSS FLOAT,
  GYSELLA_GOODBROTHER VARCHAR2(3963),
  ERMESANDE_HAYFORD CLOB,
  RICKARD_WYLDE SMALLINT,
  VISERYS_II_TARGARYEN VARCHAR2(2290),
  HARETH INTEGER,
  JOSS_THE_GLOOM DECIMAL,
  MAG_MAR_TUN_DOH_WEG VARCHAR2(3963),
  ARYS_OAKHEART NUMERIC,
  BARSENA_BLACKHAIR FLOAT,
  MELWYS_RIVERS VARCHAR2(465),
  RUNCEL_HIGHTOWER NUMBER,
  RICHARD_FARROW FLOAT,
  MERRELL_FLORENT INTEGER,
  BUU NUMBER,
  HENLY VARCHAR2(873),
  LARRA_BLACKMONT SMALLINT,
  AZZAK SMALLINT,
  ALYSSA_ARRYN VARCHAR2(2290),
  RALF DATE,
  CORLISS_PENNY VARCHAR2(3963),
  CAYN CLOB,
  ULRICK_DAYNE VARCHAR2(873),
  MERYN_TRANT TIMESTAMP,
  REYSEN DATE,
  MARTYN_MULLENDORE FLOAT,
  COTTER_PYKE NUMBER,
  HALDER NUMBER,
  BENFRED_TALLHART FLOAT,
  CRAGHAS_DRAHAR SMALLINT,
  LORENT_MARBRAND DECIMAL,
  ARRON TIMESTAMP,
  ARLAN_OF_PENNYTREE DATE,
  RAINBOW_KNIGHT INTEGER,
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  PECKLEDON_ID VARCHAR2(36),
  CRESSEY_ID VARCHAR2(36)
);

CREATE TABLE CRESSEY (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  OTHOR DATE,
  LORREN NUMERIC,
  BELDECAR FLOAT,
  HARRY_SAWYER DATE,
  REYNARD_WEBBER INTEGER,
  LYNESSE_HIGHTOWER NUMBER,
  SAILORS_WIFE SMALLINT,
  RICKARD_TYRELL VARCHAR2(2290),
  CLUBFOOT_KARL VARCHAR2(465),
  KYM INTEGER,
  SOREN_SHIELDBREAKER FLOAT,
  ARWYN_FREY VARCHAR2(2290),
  ELLARIA_SAND VARCHAR2(2622),
  RHAELLA_TARGARYEN VARCHAR2(2290),
  TYENE_SAND VARCHAR2(873),
  ROB NUMBER,
  LEWYS_PIPER NUMERIC,
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  GAUNT_ID VARCHAR2(36)
);

ALTER TABLE DAYNE_OF_STARFALL ADD CONSTRAINT DAYNE_OF_STARFALL_PK PRIMARY KEY (ID);

ALTER TABLE GAUNT ADD CONSTRAINT GAUNT_PK PRIMARY KEY (ID);

ALTER TABLE PECKLEDON ADD CONSTRAINT PECKLEDON_PK PRIMARY KEY (ID);

ALTER TABLE GREYIRON_OF_ORKMONT ADD CONSTRAINT GREYIRON_OF_ORKMONT_PK PRIMARY KEY (ID);

ALTER TABLE CRESSEY ADD CONSTRAINT CRESSEY_PK PRIMARY KEY (ID);

ALTER TABLE DAYNE_OF_STARFALL ADD CONSTRAINT DAYNE_OF_STARFALL_CK CHECK (SHIERLE_SWYFT IS NOT NULL);

ALTER TABLE GAUNT ADD CONSTRAINT GAUNT_CK CHECK (OTTYN_WYTHERS IS NOT NULL);

ALTER TABLE PECKLEDON ADD CONSTRAINT PECKLEDON_CK CHECK (RAYNARD IS NOT NULL);

ALTER TABLE GREYIRON_OF_ORKMONT ADD CONSTRAINT GREYIRON_OF_ORKMONT_CK CHECK (RUNCEL_HIGHTOWER IS NOT NULL);

ALTER TABLE CRESSEY ADD CONSTRAINT CRESSEY_CK CHECK (RICKARD_TYRELL IS NOT NULL);

ALTER TABLE DAYNE_OF_STARFALL ADD CONSTRAINT DAYNE_OF_STARFALL_FK0 FOREIGN KEY (CRESSEY_ID) REFERENCES CRESSEY (ID);

ALTER TABLE DAYNE_OF_STARFALL ADD CONSTRAINT DAYNE_OF_STARFALL_FK1 FOREIGN KEY (PECKLEDON_ID) REFERENCES PECKLEDON (ID);

ALTER TABLE DAYNE_OF_STARFALL ADD CONSTRAINT DAYNE_OF_STARFALL_FK2 FOREIGN KEY (GREYIRON_OF_ORKMONT_ID) REFERENCES GREYIRON_OF_ORKMONT (ID);

ALTER TABLE GAUNT ADD CONSTRAINT GAUNT_FK0 FOREIGN KEY (PECKLEDON_ID) REFERENCES PECKLEDON (ID);

ALTER TABLE GAUNT ADD CONSTRAINT GAUNT_FK1 FOREIGN KEY (GREYIRON_OF_ORKMONT_ID) REFERENCES GREYIRON_OF_ORKMONT (ID);

ALTER TABLE PECKLEDON ADD CONSTRAINT PECKLEDON_FK0 FOREIGN KEY (CRESSEY_ID) REFERENCES CRESSEY (ID);

ALTER TABLE GREYIRON_OF_ORKMONT ADD CONSTRAINT GREYIRON_OF_ORKMONT_FK0 FOREIGN KEY (PECKLEDON_ID) REFERENCES PECKLEDON (ID);

ALTER TABLE GREYIRON_OF_ORKMONT ADD CONSTRAINT GREYIRON_OF_ORKMONT_FK1 FOREIGN KEY (CRESSEY_ID) REFERENCES CRESSEY (ID);

ALTER TABLE CRESSEY ADD CONSTRAINT CRESSEY_FK0 FOREIGN KEY (GAUNT_ID) REFERENCES GAUNT (ID);

CREATE OR REPLACE VIEW V_DAYNE_OF_STARFALL AS
  SELECT
    DAYNE_OF_STARFALL.CRESSEY_ID,
    DAYNE_OF_STARFALL.PECKLEDON_ID,
    DAYNE_OF_STARFALL.GREYIRON_OF_ORKMONT_ID
  FROM
    DAYNE_OF_STARFALL
    LEFT JOIN CRESSEY
    ON DAYNE_OF_STARFALL.CRESSEY_ID = CRESSEY.ID
    LEFT JOIN PECKLEDON
    ON DAYNE_OF_STARFALL.PECKLEDON_ID = PECKLEDON.ID
    LEFT JOIN GREYIRON_OF_ORKMONT
    ON DAYNE_OF_STARFALL.GREYIRON_OF_ORKMONT_ID = GREYIRON_OF_ORKMONT.ID;

CREATE OR REPLACE VIEW V_GREYIRON_OF_ORKMONT AS
  SELECT
    GREYIRON_OF_ORKMONT.PECKLEDON_ID,
    GREYIRON_OF_ORKMONT.CRESSEY_ID
  FROM
    GREYIRON_OF_ORKMONT
    LEFT JOIN PECKLEDON
    ON GREYIRON_OF_ORKMONT.PECKLEDON_ID = PECKLEDON.ID
    LEFT JOIN CRESSEY
    ON GREYIRON_OF_ORKMONT.CRESSEY_ID = CRESSEY.ID;

CREATE OR REPLACE VIEW V_GAUNT AS
  SELECT
    GAUNT.PECKLEDON_ID,
    GAUNT.GREYIRON_OF_ORKMONT_ID
  FROM
    GAUNT
    LEFT JOIN PECKLEDON
    ON GAUNT.PECKLEDON_ID = PECKLEDON.ID
    LEFT JOIN GREYIRON_OF_ORKMONT
    ON GAUNT.GREYIRON_OF_ORKMONT_ID = GREYIRON_OF_ORKMONT.ID;

CREATE MATERIALIZED VIEW MV_DAYNE_OF_STARFALL AS
  SELECT
    DAYNE_OF_STARFALL.CRESSEY_ID,
    DAYNE_OF_STARFALL.PECKLEDON_ID,
    DAYNE_OF_STARFALL.GREYIRON_OF_ORKMONT_ID
  FROM
    DAYNE_OF_STARFALL
    LEFT JOIN CRESSEY
    ON DAYNE_OF_STARFALL.CRESSEY_ID = CRESSEY.ID
    LEFT JOIN PECKLEDON
    ON DAYNE_OF_STARFALL.PECKLEDON_ID = PECKLEDON.ID
    LEFT JOIN GREYIRON_OF_ORKMONT
    ON DAYNE_OF_STARFALL.GREYIRON_OF_ORKMONT_ID = GREYIRON_OF_ORKMONT.ID;

CREATE MATERIALIZED VIEW MV_GREYIRON_OF_ORKMONT AS
  SELECT
    GREYIRON_OF_ORKMONT.PECKLEDON_ID,
    GREYIRON_OF_ORKMONT.CRESSEY_ID
  FROM
    GREYIRON_OF_ORKMONT
    LEFT JOIN PECKLEDON
    ON GREYIRON_OF_ORKMONT.PECKLEDON_ID = PECKLEDON.ID
    LEFT JOIN CRESSEY
    ON GREYIRON_OF_ORKMONT.CRESSEY_ID = CRESSEY.ID;

CREATE MATERIALIZED VIEW MV_GAUNT AS
  SELECT
    GAUNT.PECKLEDON_ID,
    GAUNT.GREYIRON_OF_ORKMONT_ID
  FROM
    GAUNT
    LEFT JOIN PECKLEDON
    ON GAUNT.PECKLEDON_ID = PECKLEDON.ID
    LEFT JOIN GREYIRON_OF_ORKMONT
    ON GAUNT.GREYIRON_OF_ORKMONT_ID = GREYIRON_OF_ORKMONT.ID;

CREATE OR REPLACE PROCEDURE PRINT_DAYNE_OF_STARFALL(
  P_ID VARCHAR2
) AS
  V_RESULT DAYNE_OF_STARFALL%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    DAYNE_OF_STARFALL
  WHERE
    DAYNE_OF_STARFALL.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.TOBBOT
    || ' '
    || V_RESULT.DRYN
    || ' '
    || V_RESULT.VICTOR_TYRELL
    || ' '
    || V_RESULT.ROSLIN_FREY
    || ' '
    || V_RESULT.NORREN
    || ' '
    || V_RESULT.JORAH_MORMONT
    || ' '
    || V_RESULT.BORCAS
    || ' '
    || V_RESULT.MARYA_SEAWORTH
    || ' '
    || V_RESULT.GARRETT_PAEGE
    || ' '
    || V_RESULT.VAEMOND_VELARYON
    || ' '
    || V_RESULT.MEIZO_MAHR
    || ' '
    || V_RESULT.DAGON_GREYJOY
    || ' '
    || V_RESULT.STEFFON_BARATHEON
    || ' '
    || V_RESULT.ARRYK
    || ' '
    || V_RESULT.DAVEN_LANNISTER
    || ' '
    || V_RESULT.TRISTIFER_BOTLEY
    || ' '
    || V_RESULT.GYLBERT_FARWYND
    || ' '
    || V_RESULT.NYMERIA
    || ' '
    || V_RESULT.DAMON_SHETT
    || ' '
    || V_RESULT.AEMON_BLACKFYRE
    || ' '
    || V_RESULT.TRISTON_FARWYND
    || ' '
    || V_RESULT.EDRIC_DAYNE
    || ' '
    || V_RESULT.ROBERT_ARRYN
    || ' '
    || V_RESULT.ANDREY_CHARLTON
    || ' '
    || V_RESULT.WALDER_VANCE
    || ' '
    || V_RESULT.JHEZANE
    || ' '
    || V_RESULT.MUSHROOM
    || ' '
    || V_RESULT.EON_HUNTER
    || ' '
    || V_RESULT.TOMMEN_COSTAYNE
    || ' '
    || V_RESULT.SHIERLE_SWYFT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.CRESSEY_ID
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.GREYIRON_OF_ORKMONT_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PRINT_GAUNT(
  P_ID VARCHAR2
) AS
  V_RESULT GAUNT%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    GAUNT
  WHERE
    GAUNT.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ADDAM_OSGREY
    || ' '
    || V_RESULT.WARRYN_BEESBURY
    || ' '
    || V_RESULT.JONNEL_STARK
    || ' '
    || V_RESULT.XHONDO
    || ' '
    || V_RESULT.ALESTER_FLORENT
    || ' '
    || V_RESULT.DAVOS_SEAWORTH
    || ' '
    || V_RESULT.LIKELY_LUKE
    || ' '
    || V_RESULT.TERRO
    || ' '
    || V_RESULT.MEZZARA
    || ' '
    || V_RESULT.SHERRIT
    || ' '
    || V_RESULT.RAYMUN_DARRY
    || ' '
    || V_RESULT.OTTYN_WYTHERS
    || ' '
    || V_RESULT.ORMOND
    || ' '
    || V_RESULT.DICK
    || ' '
    || V_RESULT.ALESANDER_STAEDMON
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.GREYIRON_OF_ORKMONT_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PRINT_PECKLEDON(
  P_ID VARCHAR2
) AS
  V_RESULT PECKLEDON%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    PECKLEDON
  WHERE
    PECKLEDON.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MOTHER_MOLE
    || ' '
    || V_RESULT.HARLON_GREYJOY
    || ' '
    || V_RESULT.CEDRIK_STORM
    || ' '
    || V_RESULT.RAYNARD
    || ' '
    || V_RESULT.ANDRIK
    || ' '
    || V_RESULT.MORREC
    || ' '
    || V_RESULT.ALYN_FREY
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.CRESSEY_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PRINT_GREYIRON_OF_ORKMONT(
  P_ID VARCHAR2
) AS
  V_RESULT GREYIRON_OF_ORKMONT%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    GREYIRON_OF_ORKMONT
  WHERE
    GREYIRON_OF_ORKMONT.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ROBIN_FLINT
    || ' '
    || V_RESULT.EBROSE
    || ' '
    || V_RESULT.EBBEN
    || ' '
    || V_RESULT.WALDER_FREY
    || ' '
    || V_RESULT.WALDA_FREY
    || ' '
    || V_RESULT.DONAL_NOYE
    || ' '
    || V_RESULT.JAYNE_BRACKEN
    || ' '
    || V_RESULT.HIGH_SPARROW
    || ' '
    || V_RESULT.TRISTON_OF_TALLY_HILL
    || ' '
    || V_RESULT.ORMUND_WYLDE
    || ' '
    || V_RESULT.AERYS_I_TARGARYEN
    || ' '
    || V_RESULT.GRAZDAN
    || ' '
    || V_RESULT.MANFRED_DONDARRION
    || ' '
    || V_RESULT.ALLISER_THORNE
    || ' '
    || V_RESULT.AEGON_TARGARYEN
    || ' '
    || V_RESULT.ERRYK
    || ' '
    || V_RESULT.RYGER_RIVERS
    || ' '
    || V_RESULT.GYLORO_DOTHARE
    || ' '
    || V_RESULT.HERBERT_BOLLING
    || ' '
    || V_RESULT.GLENDON_HEWETT
    || ' '
    || V_RESULT.JEYNE_SWANN
    || ' '
    || V_RESULT.NAERYS_TARGARYEN
    || ' '
    || V_RESULT.MAELOR_TARGARYEN
    || ' '
    || V_RESULT.HAEGON_BLACKFYRE
    || ' '
    || V_RESULT.CUGER
    || ' '
    || V_RESULT.SHIERA_SEASTAR
    || ' '
    || V_RESULT.BELIS
    || ' '
    || V_RESULT.LORREN
    || ' '
    || V_RESULT.SYLWA_PAEGE
    || ' '
    || V_RESULT.BENEDICT_BROOM
    || ' '
    || V_RESULT.LENNOCKS
    || ' '
    || V_RESULT.GERRICK_KINGSBLOOD
    || ' '
    || V_RESULT.GARTH_TYRELL
    || ' '
    || V_RESULT.STONESNAKE
    || ' '
    || V_RESULT.DONNOR_STARK
    || ' '
    || V_RESULT.ALYN_VELARYON
    || ' '
    || V_RESULT.SYMOND_FREY
    || ' '
    || V_RESULT.EDWYN_OSGREY
    || ' '
    || V_RESULT.RHAENA_TARGARYEN
    || ' '
    || V_RESULT.TIM_TANGLETONGUE
    || ' '
    || V_RESULT.QYLE
    || ' '
    || V_RESULT.MYA_STONE
    || ' '
    || V_RESULT.URRON_GREYIRON
    || ' '
    || V_RESULT.BETHANY_BOLTON
    || ' '
    || V_RESULT.AEMON_COSTAYNE
    || ' '
    || V_RESULT.KYLEG_OF_THE_WOODEN_EAR
    || ' '
    || V_RESULT.MORTON_WAYNWOOD
    || ' '
    || V_RESULT.TORWYND
    || ' '
    || V_RESULT.LORD_CAFFEREN
    || ' '
    || V_RESULT.JON_PENNY
    || ' '
    || V_RESULT.EZZARA
    || ' '
    || V_RESULT.LARK
    || ' '
    || V_RESULT.ALYSANNE_BULWER
    || ' '
    || V_RESULT.HOSMAN_NORCROSS
    || ' '
    || V_RESULT.GYSELLA_GOODBROTHER
    || ' '
    || V_RESULT.ERMESANDE_HAYFORD
    || ' '
    || V_RESULT.RICKARD_WYLDE
    || ' '
    || V_RESULT.VISERYS_II_TARGARYEN
    || ' '
    || V_RESULT.HARETH
    || ' '
    || V_RESULT.JOSS_THE_GLOOM
    || ' '
    || V_RESULT.MAG_MAR_TUN_DOH_WEG
    || ' '
    || V_RESULT.ARYS_OAKHEART
    || ' '
    || V_RESULT.BARSENA_BLACKHAIR
    || ' '
    || V_RESULT.MELWYS_RIVERS
    || ' '
    || V_RESULT.RUNCEL_HIGHTOWER
    || ' '
    || V_RESULT.RICHARD_FARROW
    || ' '
    || V_RESULT.MERRELL_FLORENT
    || ' '
    || V_RESULT.BUU
    || ' '
    || V_RESULT.HENLY
    || ' '
    || V_RESULT.LARRA_BLACKMONT
    || ' '
    || V_RESULT.AZZAK
    || ' '
    || V_RESULT.ALYSSA_ARRYN
    || ' '
    || V_RESULT.RALF
    || ' '
    || V_RESULT.CORLISS_PENNY
    || ' '
    || V_RESULT.CAYN
    || ' '
    || V_RESULT.ULRICK_DAYNE
    || ' '
    || V_RESULT.MERYN_TRANT
    || ' '
    || V_RESULT.REYSEN
    || ' '
    || V_RESULT.MARTYN_MULLENDORE
    || ' '
    || V_RESULT.COTTER_PYKE
    || ' '
    || V_RESULT.HALDER
    || ' '
    || V_RESULT.BENFRED_TALLHART
    || ' '
    || V_RESULT.CRAGHAS_DRAHAR
    || ' '
    || V_RESULT.LORENT_MARBRAND
    || ' '
    || V_RESULT.ARRON
    || ' '
    || V_RESULT.ARLAN_OF_PENNYTREE
    || ' '
    || V_RESULT.RAINBOW_KNIGHT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.CRESSEY_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PRINT_CRESSEY(
  P_ID VARCHAR2
) AS
  V_RESULT CRESSEY%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    CRESSEY
  WHERE
    CRESSEY.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.OTHOR
    || ' '
    || V_RESULT.LORREN
    || ' '
    || V_RESULT.BELDECAR
    || ' '
    || V_RESULT.HARRY_SAWYER
    || ' '
    || V_RESULT.REYNARD_WEBBER
    || ' '
    || V_RESULT.LYNESSE_HIGHTOWER
    || ' '
    || V_RESULT.SAILORS_WIFE
    || ' '
    || V_RESULT.RICKARD_TYRELL
    || ' '
    || V_RESULT.CLUBFOOT_KARL
    || ' '
    || V_RESULT.KYM
    || ' '
    || V_RESULT.SOREN_SHIELDBREAKER
    || ' '
    || V_RESULT.ARWYN_FREY
    || ' '
    || V_RESULT.ELLARIA_SAND
    || ' '
    || V_RESULT.RHAELLA_TARGARYEN
    || ' '
    || V_RESULT.TYENE_SAND
    || ' '
    || V_RESULT.ROB
    || ' '
    || V_RESULT.LEWYS_PIPER
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.GAUNT_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE FUNCTION GET_DAYNE_OF_STARFALL(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT DAYNE_OF_STARFALL%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    DAYNE_OF_STARFALL
  WHERE
    DAYNE_OF_STARFALL.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.TOBBOT
    || ' '
    || V_RESULT.DRYN
    || ' '
    || V_RESULT.VICTOR_TYRELL
    || ' '
    || V_RESULT.ROSLIN_FREY
    || ' '
    || V_RESULT.NORREN
    || ' '
    || V_RESULT.JORAH_MORMONT
    || ' '
    || V_RESULT.BORCAS
    || ' '
    || V_RESULT.MARYA_SEAWORTH
    || ' '
    || V_RESULT.GARRETT_PAEGE
    || ' '
    || V_RESULT.VAEMOND_VELARYON
    || ' '
    || V_RESULT.MEIZO_MAHR
    || ' '
    || V_RESULT.DAGON_GREYJOY
    || ' '
    || V_RESULT.STEFFON_BARATHEON
    || ' '
    || V_RESULT.ARRYK
    || ' '
    || V_RESULT.DAVEN_LANNISTER
    || ' '
    || V_RESULT.TRISTIFER_BOTLEY
    || ' '
    || V_RESULT.GYLBERT_FARWYND
    || ' '
    || V_RESULT.NYMERIA
    || ' '
    || V_RESULT.DAMON_SHETT
    || ' '
    || V_RESULT.AEMON_BLACKFYRE
    || ' '
    || V_RESULT.TRISTON_FARWYND
    || ' '
    || V_RESULT.EDRIC_DAYNE
    || ' '
    || V_RESULT.ROBERT_ARRYN
    || ' '
    || V_RESULT.ANDREY_CHARLTON
    || ' '
    || V_RESULT.WALDER_VANCE
    || ' '
    || V_RESULT.JHEZANE
    || ' '
    || V_RESULT.MUSHROOM
    || ' '
    || V_RESULT.EON_HUNTER
    || ' '
    || V_RESULT.TOMMEN_COSTAYNE
    || ' '
    || V_RESULT.SHIERLE_SWYFT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.CRESSEY_ID
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.GREYIRON_OF_ORKMONT_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GET_GAUNT(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT GAUNT%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    GAUNT
  WHERE
    GAUNT.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ADDAM_OSGREY
    || ' '
    || V_RESULT.WARRYN_BEESBURY
    || ' '
    || V_RESULT.JONNEL_STARK
    || ' '
    || V_RESULT.XHONDO
    || ' '
    || V_RESULT.ALESTER_FLORENT
    || ' '
    || V_RESULT.DAVOS_SEAWORTH
    || ' '
    || V_RESULT.LIKELY_LUKE
    || ' '
    || V_RESULT.TERRO
    || ' '
    || V_RESULT.MEZZARA
    || ' '
    || V_RESULT.SHERRIT
    || ' '
    || V_RESULT.RAYMUN_DARRY
    || ' '
    || V_RESULT.OTTYN_WYTHERS
    || ' '
    || V_RESULT.ORMOND
    || ' '
    || V_RESULT.DICK
    || ' '
    || V_RESULT.ALESANDER_STAEDMON
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.GREYIRON_OF_ORKMONT_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GET_PECKLEDON(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT PECKLEDON%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    PECKLEDON
  WHERE
    PECKLEDON.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MOTHER_MOLE
    || ' '
    || V_RESULT.HARLON_GREYJOY
    || ' '
    || V_RESULT.CEDRIK_STORM
    || ' '
    || V_RESULT.RAYNARD
    || ' '
    || V_RESULT.ANDRIK
    || ' '
    || V_RESULT.MORREC
    || ' '
    || V_RESULT.ALYN_FREY
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.CRESSEY_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GET_GREYIRON_OF_ORKMONT(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT GREYIRON_OF_ORKMONT%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    GREYIRON_OF_ORKMONT
  WHERE
    GREYIRON_OF_ORKMONT.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ROBIN_FLINT
    || ' '
    || V_RESULT.EBROSE
    || ' '
    || V_RESULT.EBBEN
    || ' '
    || V_RESULT.WALDER_FREY
    || ' '
    || V_RESULT.WALDA_FREY
    || ' '
    || V_RESULT.DONAL_NOYE
    || ' '
    || V_RESULT.JAYNE_BRACKEN
    || ' '
    || V_RESULT.HIGH_SPARROW
    || ' '
    || V_RESULT.TRISTON_OF_TALLY_HILL
    || ' '
    || V_RESULT.ORMUND_WYLDE
    || ' '
    || V_RESULT.AERYS_I_TARGARYEN
    || ' '
    || V_RESULT.GRAZDAN
    || ' '
    || V_RESULT.MANFRED_DONDARRION
    || ' '
    || V_RESULT.ALLISER_THORNE
    || ' '
    || V_RESULT.AEGON_TARGARYEN
    || ' '
    || V_RESULT.ERRYK
    || ' '
    || V_RESULT.RYGER_RIVERS
    || ' '
    || V_RESULT.GYLORO_DOTHARE
    || ' '
    || V_RESULT.HERBERT_BOLLING
    || ' '
    || V_RESULT.GLENDON_HEWETT
    || ' '
    || V_RESULT.JEYNE_SWANN
    || ' '
    || V_RESULT.NAERYS_TARGARYEN
    || ' '
    || V_RESULT.MAELOR_TARGARYEN
    || ' '
    || V_RESULT.HAEGON_BLACKFYRE
    || ' '
    || V_RESULT.CUGER
    || ' '
    || V_RESULT.SHIERA_SEASTAR
    || ' '
    || V_RESULT.BELIS
    || ' '
    || V_RESULT.LORREN
    || ' '
    || V_RESULT.SYLWA_PAEGE
    || ' '
    || V_RESULT.BENEDICT_BROOM
    || ' '
    || V_RESULT.LENNOCKS
    || ' '
    || V_RESULT.GERRICK_KINGSBLOOD
    || ' '
    || V_RESULT.GARTH_TYRELL
    || ' '
    || V_RESULT.STONESNAKE
    || ' '
    || V_RESULT.DONNOR_STARK
    || ' '
    || V_RESULT.ALYN_VELARYON
    || ' '
    || V_RESULT.SYMOND_FREY
    || ' '
    || V_RESULT.EDWYN_OSGREY
    || ' '
    || V_RESULT.RHAENA_TARGARYEN
    || ' '
    || V_RESULT.TIM_TANGLETONGUE
    || ' '
    || V_RESULT.QYLE
    || ' '
    || V_RESULT.MYA_STONE
    || ' '
    || V_RESULT.URRON_GREYIRON
    || ' '
    || V_RESULT.BETHANY_BOLTON
    || ' '
    || V_RESULT.AEMON_COSTAYNE
    || ' '
    || V_RESULT.KYLEG_OF_THE_WOODEN_EAR
    || ' '
    || V_RESULT.MORTON_WAYNWOOD
    || ' '
    || V_RESULT.TORWYND
    || ' '
    || V_RESULT.LORD_CAFFEREN
    || ' '
    || V_RESULT.JON_PENNY
    || ' '
    || V_RESULT.EZZARA
    || ' '
    || V_RESULT.LARK
    || ' '
    || V_RESULT.ALYSANNE_BULWER
    || ' '
    || V_RESULT.HOSMAN_NORCROSS
    || ' '
    || V_RESULT.GYSELLA_GOODBROTHER
    || ' '
    || V_RESULT.ERMESANDE_HAYFORD
    || ' '
    || V_RESULT.RICKARD_WYLDE
    || ' '
    || V_RESULT.VISERYS_II_TARGARYEN
    || ' '
    || V_RESULT.HARETH
    || ' '
    || V_RESULT.JOSS_THE_GLOOM
    || ' '
    || V_RESULT.MAG_MAR_TUN_DOH_WEG
    || ' '
    || V_RESULT.ARYS_OAKHEART
    || ' '
    || V_RESULT.BARSENA_BLACKHAIR
    || ' '
    || V_RESULT.MELWYS_RIVERS
    || ' '
    || V_RESULT.RUNCEL_HIGHTOWER
    || ' '
    || V_RESULT.RICHARD_FARROW
    || ' '
    || V_RESULT.MERRELL_FLORENT
    || ' '
    || V_RESULT.BUU
    || ' '
    || V_RESULT.HENLY
    || ' '
    || V_RESULT.LARRA_BLACKMONT
    || ' '
    || V_RESULT.AZZAK
    || ' '
    || V_RESULT.ALYSSA_ARRYN
    || ' '
    || V_RESULT.RALF
    || ' '
    || V_RESULT.CORLISS_PENNY
    || ' '
    || V_RESULT.CAYN
    || ' '
    || V_RESULT.ULRICK_DAYNE
    || ' '
    || V_RESULT.MERYN_TRANT
    || ' '
    || V_RESULT.REYSEN
    || ' '
    || V_RESULT.MARTYN_MULLENDORE
    || ' '
    || V_RESULT.COTTER_PYKE
    || ' '
    || V_RESULT.HALDER
    || ' '
    || V_RESULT.BENFRED_TALLHART
    || ' '
    || V_RESULT.CRAGHAS_DRAHAR
    || ' '
    || V_RESULT.LORENT_MARBRAND
    || ' '
    || V_RESULT.ARRON
    || ' '
    || V_RESULT.ARLAN_OF_PENNYTREE
    || ' '
    || V_RESULT.RAINBOW_KNIGHT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.CRESSEY_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GET_CRESSEY(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT CRESSEY%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    CRESSEY
  WHERE
    CRESSEY.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.OTHOR
    || ' '
    || V_RESULT.LORREN
    || ' '
    || V_RESULT.BELDECAR
    || ' '
    || V_RESULT.HARRY_SAWYER
    || ' '
    || V_RESULT.REYNARD_WEBBER
    || ' '
    || V_RESULT.LYNESSE_HIGHTOWER
    || ' '
    || V_RESULT.SAILORS_WIFE
    || ' '
    || V_RESULT.RICKARD_TYRELL
    || ' '
    || V_RESULT.CLUBFOOT_KARL
    || ' '
    || V_RESULT.KYM
    || ' '
    || V_RESULT.SOREN_SHIELDBREAKER
    || ' '
    || V_RESULT.ARWYN_FREY
    || ' '
    || V_RESULT.ELLARIA_SAND
    || ' '
    || V_RESULT.RHAELLA_TARGARYEN
    || ' '
    || V_RESULT.TYENE_SAND
    || ' '
    || V_RESULT.ROB
    || ' '
    || V_RESULT.LEWYS_PIPER
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.GAUNT_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE PACKAGE PKG_DAYNE_OF_STARFALL AS
  FUNCTION GET_DAYNE_OF_STARFALL(
    P_ID VARCHAR2
  ) RETURN VARCHAR2;
  PROCEDURE PRINT_DAYNE_OF_STARFALL(
    P_ID VARCHAR2
  );
END PKG_DAYNE_OF_STARFALL;
CREATE OR REPLACE PACKAGE BODY PKG_DAYNE_OF_STARFALL AS PROCEDURE PRINT_DAYNE_OF_STARFALL(
  P_ID VARCHAR2
) AS
  V_RESULT DAYNE_OF_STARFALL%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    DAYNE_OF_STARFALL
  WHERE
    DAYNE_OF_STARFALL.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.TOBBOT
    || ' '
    || V_RESULT.DRYN
    || ' '
    || V_RESULT.VICTOR_TYRELL
    || ' '
    || V_RESULT.ROSLIN_FREY
    || ' '
    || V_RESULT.NORREN
    || ' '
    || V_RESULT.JORAH_MORMONT
    || ' '
    || V_RESULT.BORCAS
    || ' '
    || V_RESULT.MARYA_SEAWORTH
    || ' '
    || V_RESULT.GARRETT_PAEGE
    || ' '
    || V_RESULT.VAEMOND_VELARYON
    || ' '
    || V_RESULT.MEIZO_MAHR
    || ' '
    || V_RESULT.DAGON_GREYJOY
    || ' '
    || V_RESULT.STEFFON_BARATHEON
    || ' '
    || V_RESULT.ARRYK
    || ' '
    || V_RESULT.DAVEN_LANNISTER
    || ' '
    || V_RESULT.TRISTIFER_BOTLEY
    || ' '
    || V_RESULT.GYLBERT_FARWYND
    || ' '
    || V_RESULT.NYMERIA
    || ' '
    || V_RESULT.DAMON_SHETT
    || ' '
    || V_RESULT.AEMON_BLACKFYRE
    || ' '
    || V_RESULT.TRISTON_FARWYND
    || ' '
    || V_RESULT.EDRIC_DAYNE
    || ' '
    || V_RESULT.ROBERT_ARRYN
    || ' '
    || V_RESULT.ANDREY_CHARLTON
    || ' '
    || V_RESULT.WALDER_VANCE
    || ' '
    || V_RESULT.JHEZANE
    || ' '
    || V_RESULT.MUSHROOM
    || ' '
    || V_RESULT.EON_HUNTER
    || ' '
    || V_RESULT.TOMMEN_COSTAYNE
    || ' '
    || V_RESULT.SHIERLE_SWYFT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.CRESSEY_ID
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.GREYIRON_OF_ORKMONT_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_DAYNE_OF_STARFALL(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT DAYNE_OF_STARFALL%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    DAYNE_OF_STARFALL
  WHERE
    DAYNE_OF_STARFALL.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.TOBBOT
    || ' '
    || V_RESULT.DRYN
    || ' '
    || V_RESULT.VICTOR_TYRELL
    || ' '
    || V_RESULT.ROSLIN_FREY
    || ' '
    || V_RESULT.NORREN
    || ' '
    || V_RESULT.JORAH_MORMONT
    || ' '
    || V_RESULT.BORCAS
    || ' '
    || V_RESULT.MARYA_SEAWORTH
    || ' '
    || V_RESULT.GARRETT_PAEGE
    || ' '
    || V_RESULT.VAEMOND_VELARYON
    || ' '
    || V_RESULT.MEIZO_MAHR
    || ' '
    || V_RESULT.DAGON_GREYJOY
    || ' '
    || V_RESULT.STEFFON_BARATHEON
    || ' '
    || V_RESULT.ARRYK
    || ' '
    || V_RESULT.DAVEN_LANNISTER
    || ' '
    || V_RESULT.TRISTIFER_BOTLEY
    || ' '
    || V_RESULT.GYLBERT_FARWYND
    || ' '
    || V_RESULT.NYMERIA
    || ' '
    || V_RESULT.DAMON_SHETT
    || ' '
    || V_RESULT.AEMON_BLACKFYRE
    || ' '
    || V_RESULT.TRISTON_FARWYND
    || ' '
    || V_RESULT.EDRIC_DAYNE
    || ' '
    || V_RESULT.ROBERT_ARRYN
    || ' '
    || V_RESULT.ANDREY_CHARLTON
    || ' '
    || V_RESULT.WALDER_VANCE
    || ' '
    || V_RESULT.JHEZANE
    || ' '
    || V_RESULT.MUSHROOM
    || ' '
    || V_RESULT.EON_HUNTER
    || ' '
    || V_RESULT.TOMMEN_COSTAYNE
    || ' '
    || V_RESULT.SHIERLE_SWYFT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.CRESSEY_ID
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.GREYIRON_OF_ORKMONT_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_DAYNE_OF_STARFALL;
CREATE OR REPLACE PACKAGE PKG_GAUNT AS FUNCTION GET_GAUNT(
  P_ID VARCHAR2
) RETURN VARCHAR2;
PROCEDURE PRINT_GAUNT(
  P_ID VARCHAR2
);
END PKG_GAUNT;
CREATE OR REPLACE PACKAGE BODY PKG_GAUNT AS PROCEDURE PRINT_GAUNT(
  P_ID VARCHAR2
) AS
  V_RESULT GAUNT%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    GAUNT
  WHERE
    GAUNT.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ADDAM_OSGREY
    || ' '
    || V_RESULT.WARRYN_BEESBURY
    || ' '
    || V_RESULT.JONNEL_STARK
    || ' '
    || V_RESULT.XHONDO
    || ' '
    || V_RESULT.ALESTER_FLORENT
    || ' '
    || V_RESULT.DAVOS_SEAWORTH
    || ' '
    || V_RESULT.LIKELY_LUKE
    || ' '
    || V_RESULT.TERRO
    || ' '
    || V_RESULT.MEZZARA
    || ' '
    || V_RESULT.SHERRIT
    || ' '
    || V_RESULT.RAYMUN_DARRY
    || ' '
    || V_RESULT.OTTYN_WYTHERS
    || ' '
    || V_RESULT.ORMOND
    || ' '
    || V_RESULT.DICK
    || ' '
    || V_RESULT.ALESANDER_STAEDMON
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.GREYIRON_OF_ORKMONT_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_GAUNT(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT GAUNT%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    GAUNT
  WHERE
    GAUNT.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ADDAM_OSGREY
    || ' '
    || V_RESULT.WARRYN_BEESBURY
    || ' '
    || V_RESULT.JONNEL_STARK
    || ' '
    || V_RESULT.XHONDO
    || ' '
    || V_RESULT.ALESTER_FLORENT
    || ' '
    || V_RESULT.DAVOS_SEAWORTH
    || ' '
    || V_RESULT.LIKELY_LUKE
    || ' '
    || V_RESULT.TERRO
    || ' '
    || V_RESULT.MEZZARA
    || ' '
    || V_RESULT.SHERRIT
    || ' '
    || V_RESULT.RAYMUN_DARRY
    || ' '
    || V_RESULT.OTTYN_WYTHERS
    || ' '
    || V_RESULT.ORMOND
    || ' '
    || V_RESULT.DICK
    || ' '
    || V_RESULT.ALESANDER_STAEDMON
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.GREYIRON_OF_ORKMONT_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_GAUNT;
CREATE OR REPLACE PACKAGE PKG_PECKLEDON AS FUNCTION GET_PECKLEDON(
  P_ID VARCHAR2
) RETURN VARCHAR2;
PROCEDURE PRINT_PECKLEDON(
  P_ID VARCHAR2
);
END PKG_PECKLEDON;
CREATE OR REPLACE PACKAGE BODY PKG_PECKLEDON AS PROCEDURE PRINT_PECKLEDON(
  P_ID VARCHAR2
) AS
  V_RESULT PECKLEDON%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    PECKLEDON
  WHERE
    PECKLEDON.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MOTHER_MOLE
    || ' '
    || V_RESULT.HARLON_GREYJOY
    || ' '
    || V_RESULT.CEDRIK_STORM
    || ' '
    || V_RESULT.RAYNARD
    || ' '
    || V_RESULT.ANDRIK
    || ' '
    || V_RESULT.MORREC
    || ' '
    || V_RESULT.ALYN_FREY
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.CRESSEY_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_PECKLEDON(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT PECKLEDON%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    PECKLEDON
  WHERE
    PECKLEDON.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MOTHER_MOLE
    || ' '
    || V_RESULT.HARLON_GREYJOY
    || ' '
    || V_RESULT.CEDRIK_STORM
    || ' '
    || V_RESULT.RAYNARD
    || ' '
    || V_RESULT.ANDRIK
    || ' '
    || V_RESULT.MORREC
    || ' '
    || V_RESULT.ALYN_FREY
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.CRESSEY_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_PECKLEDON;
CREATE OR REPLACE PACKAGE PKG_GREYIRON_OF_ORKMONT AS FUNCTION GET_GREYIRON_OF_ORKMONT(
  P_ID VARCHAR2
) RETURN VARCHAR2;
PROCEDURE PRINT_GREYIRON_OF_ORKMONT(
  P_ID VARCHAR2
);
END PKG_GREYIRON_OF_ORKMONT;
CREATE OR REPLACE PACKAGE BODY PKG_GREYIRON_OF_ORKMONT AS PROCEDURE PRINT_GREYIRON_OF_ORKMONT(
  P_ID VARCHAR2
) AS
  V_RESULT GREYIRON_OF_ORKMONT%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    GREYIRON_OF_ORKMONT
  WHERE
    GREYIRON_OF_ORKMONT.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ROBIN_FLINT
    || ' '
    || V_RESULT.EBROSE
    || ' '
    || V_RESULT.EBBEN
    || ' '
    || V_RESULT.WALDER_FREY
    || ' '
    || V_RESULT.WALDA_FREY
    || ' '
    || V_RESULT.DONAL_NOYE
    || ' '
    || V_RESULT.JAYNE_BRACKEN
    || ' '
    || V_RESULT.HIGH_SPARROW
    || ' '
    || V_RESULT.TRISTON_OF_TALLY_HILL
    || ' '
    || V_RESULT.ORMUND_WYLDE
    || ' '
    || V_RESULT.AERYS_I_TARGARYEN
    || ' '
    || V_RESULT.GRAZDAN
    || ' '
    || V_RESULT.MANFRED_DONDARRION
    || ' '
    || V_RESULT.ALLISER_THORNE
    || ' '
    || V_RESULT.AEGON_TARGARYEN
    || ' '
    || V_RESULT.ERRYK
    || ' '
    || V_RESULT.RYGER_RIVERS
    || ' '
    || V_RESULT.GYLORO_DOTHARE
    || ' '
    || V_RESULT.HERBERT_BOLLING
    || ' '
    || V_RESULT.GLENDON_HEWETT
    || ' '
    || V_RESULT.JEYNE_SWANN
    || ' '
    || V_RESULT.NAERYS_TARGARYEN
    || ' '
    || V_RESULT.MAELOR_TARGARYEN
    || ' '
    || V_RESULT.HAEGON_BLACKFYRE
    || ' '
    || V_RESULT.CUGER
    || ' '
    || V_RESULT.SHIERA_SEASTAR
    || ' '
    || V_RESULT.BELIS
    || ' '
    || V_RESULT.LORREN
    || ' '
    || V_RESULT.SYLWA_PAEGE
    || ' '
    || V_RESULT.BENEDICT_BROOM
    || ' '
    || V_RESULT.LENNOCKS
    || ' '
    || V_RESULT.GERRICK_KINGSBLOOD
    || ' '
    || V_RESULT.GARTH_TYRELL
    || ' '
    || V_RESULT.STONESNAKE
    || ' '
    || V_RESULT.DONNOR_STARK
    || ' '
    || V_RESULT.ALYN_VELARYON
    || ' '
    || V_RESULT.SYMOND_FREY
    || ' '
    || V_RESULT.EDWYN_OSGREY
    || ' '
    || V_RESULT.RHAENA_TARGARYEN
    || ' '
    || V_RESULT.TIM_TANGLETONGUE
    || ' '
    || V_RESULT.QYLE
    || ' '
    || V_RESULT.MYA_STONE
    || ' '
    || V_RESULT.URRON_GREYIRON
    || ' '
    || V_RESULT.BETHANY_BOLTON
    || ' '
    || V_RESULT.AEMON_COSTAYNE
    || ' '
    || V_RESULT.KYLEG_OF_THE_WOODEN_EAR
    || ' '
    || V_RESULT.MORTON_WAYNWOOD
    || ' '
    || V_RESULT.TORWYND
    || ' '
    || V_RESULT.LORD_CAFFEREN
    || ' '
    || V_RESULT.JON_PENNY
    || ' '
    || V_RESULT.EZZARA
    || ' '
    || V_RESULT.LARK
    || ' '
    || V_RESULT.ALYSANNE_BULWER
    || ' '
    || V_RESULT.HOSMAN_NORCROSS
    || ' '
    || V_RESULT.GYSELLA_GOODBROTHER
    || ' '
    || V_RESULT.ERMESANDE_HAYFORD
    || ' '
    || V_RESULT.RICKARD_WYLDE
    || ' '
    || V_RESULT.VISERYS_II_TARGARYEN
    || ' '
    || V_RESULT.HARETH
    || ' '
    || V_RESULT.JOSS_THE_GLOOM
    || ' '
    || V_RESULT.MAG_MAR_TUN_DOH_WEG
    || ' '
    || V_RESULT.ARYS_OAKHEART
    || ' '
    || V_RESULT.BARSENA_BLACKHAIR
    || ' '
    || V_RESULT.MELWYS_RIVERS
    || ' '
    || V_RESULT.RUNCEL_HIGHTOWER
    || ' '
    || V_RESULT.RICHARD_FARROW
    || ' '
    || V_RESULT.MERRELL_FLORENT
    || ' '
    || V_RESULT.BUU
    || ' '
    || V_RESULT.HENLY
    || ' '
    || V_RESULT.LARRA_BLACKMONT
    || ' '
    || V_RESULT.AZZAK
    || ' '
    || V_RESULT.ALYSSA_ARRYN
    || ' '
    || V_RESULT.RALF
    || ' '
    || V_RESULT.CORLISS_PENNY
    || ' '
    || V_RESULT.CAYN
    || ' '
    || V_RESULT.ULRICK_DAYNE
    || ' '
    || V_RESULT.MERYN_TRANT
    || ' '
    || V_RESULT.REYSEN
    || ' '
    || V_RESULT.MARTYN_MULLENDORE
    || ' '
    || V_RESULT.COTTER_PYKE
    || ' '
    || V_RESULT.HALDER
    || ' '
    || V_RESULT.BENFRED_TALLHART
    || ' '
    || V_RESULT.CRAGHAS_DRAHAR
    || ' '
    || V_RESULT.LORENT_MARBRAND
    || ' '
    || V_RESULT.ARRON
    || ' '
    || V_RESULT.ARLAN_OF_PENNYTREE
    || ' '
    || V_RESULT.RAINBOW_KNIGHT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.CRESSEY_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_GREYIRON_OF_ORKMONT(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT GREYIRON_OF_ORKMONT%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    GREYIRON_OF_ORKMONT
  WHERE
    GREYIRON_OF_ORKMONT.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ROBIN_FLINT
    || ' '
    || V_RESULT.EBROSE
    || ' '
    || V_RESULT.EBBEN
    || ' '
    || V_RESULT.WALDER_FREY
    || ' '
    || V_RESULT.WALDA_FREY
    || ' '
    || V_RESULT.DONAL_NOYE
    || ' '
    || V_RESULT.JAYNE_BRACKEN
    || ' '
    || V_RESULT.HIGH_SPARROW
    || ' '
    || V_RESULT.TRISTON_OF_TALLY_HILL
    || ' '
    || V_RESULT.ORMUND_WYLDE
    || ' '
    || V_RESULT.AERYS_I_TARGARYEN
    || ' '
    || V_RESULT.GRAZDAN
    || ' '
    || V_RESULT.MANFRED_DONDARRION
    || ' '
    || V_RESULT.ALLISER_THORNE
    || ' '
    || V_RESULT.AEGON_TARGARYEN
    || ' '
    || V_RESULT.ERRYK
    || ' '
    || V_RESULT.RYGER_RIVERS
    || ' '
    || V_RESULT.GYLORO_DOTHARE
    || ' '
    || V_RESULT.HERBERT_BOLLING
    || ' '
    || V_RESULT.GLENDON_HEWETT
    || ' '
    || V_RESULT.JEYNE_SWANN
    || ' '
    || V_RESULT.NAERYS_TARGARYEN
    || ' '
    || V_RESULT.MAELOR_TARGARYEN
    || ' '
    || V_RESULT.HAEGON_BLACKFYRE
    || ' '
    || V_RESULT.CUGER
    || ' '
    || V_RESULT.SHIERA_SEASTAR
    || ' '
    || V_RESULT.BELIS
    || ' '
    || V_RESULT.LORREN
    || ' '
    || V_RESULT.SYLWA_PAEGE
    || ' '
    || V_RESULT.BENEDICT_BROOM
    || ' '
    || V_RESULT.LENNOCKS
    || ' '
    || V_RESULT.GERRICK_KINGSBLOOD
    || ' '
    || V_RESULT.GARTH_TYRELL
    || ' '
    || V_RESULT.STONESNAKE
    || ' '
    || V_RESULT.DONNOR_STARK
    || ' '
    || V_RESULT.ALYN_VELARYON
    || ' '
    || V_RESULT.SYMOND_FREY
    || ' '
    || V_RESULT.EDWYN_OSGREY
    || ' '
    || V_RESULT.RHAENA_TARGARYEN
    || ' '
    || V_RESULT.TIM_TANGLETONGUE
    || ' '
    || V_RESULT.QYLE
    || ' '
    || V_RESULT.MYA_STONE
    || ' '
    || V_RESULT.URRON_GREYIRON
    || ' '
    || V_RESULT.BETHANY_BOLTON
    || ' '
    || V_RESULT.AEMON_COSTAYNE
    || ' '
    || V_RESULT.KYLEG_OF_THE_WOODEN_EAR
    || ' '
    || V_RESULT.MORTON_WAYNWOOD
    || ' '
    || V_RESULT.TORWYND
    || ' '
    || V_RESULT.LORD_CAFFEREN
    || ' '
    || V_RESULT.JON_PENNY
    || ' '
    || V_RESULT.EZZARA
    || ' '
    || V_RESULT.LARK
    || ' '
    || V_RESULT.ALYSANNE_BULWER
    || ' '
    || V_RESULT.HOSMAN_NORCROSS
    || ' '
    || V_RESULT.GYSELLA_GOODBROTHER
    || ' '
    || V_RESULT.ERMESANDE_HAYFORD
    || ' '
    || V_RESULT.RICKARD_WYLDE
    || ' '
    || V_RESULT.VISERYS_II_TARGARYEN
    || ' '
    || V_RESULT.HARETH
    || ' '
    || V_RESULT.JOSS_THE_GLOOM
    || ' '
    || V_RESULT.MAG_MAR_TUN_DOH_WEG
    || ' '
    || V_RESULT.ARYS_OAKHEART
    || ' '
    || V_RESULT.BARSENA_BLACKHAIR
    || ' '
    || V_RESULT.MELWYS_RIVERS
    || ' '
    || V_RESULT.RUNCEL_HIGHTOWER
    || ' '
    || V_RESULT.RICHARD_FARROW
    || ' '
    || V_RESULT.MERRELL_FLORENT
    || ' '
    || V_RESULT.BUU
    || ' '
    || V_RESULT.HENLY
    || ' '
    || V_RESULT.LARRA_BLACKMONT
    || ' '
    || V_RESULT.AZZAK
    || ' '
    || V_RESULT.ALYSSA_ARRYN
    || ' '
    || V_RESULT.RALF
    || ' '
    || V_RESULT.CORLISS_PENNY
    || ' '
    || V_RESULT.CAYN
    || ' '
    || V_RESULT.ULRICK_DAYNE
    || ' '
    || V_RESULT.MERYN_TRANT
    || ' '
    || V_RESULT.REYSEN
    || ' '
    || V_RESULT.MARTYN_MULLENDORE
    || ' '
    || V_RESULT.COTTER_PYKE
    || ' '
    || V_RESULT.HALDER
    || ' '
    || V_RESULT.BENFRED_TALLHART
    || ' '
    || V_RESULT.CRAGHAS_DRAHAR
    || ' '
    || V_RESULT.LORENT_MARBRAND
    || ' '
    || V_RESULT.ARRON
    || ' '
    || V_RESULT.ARLAN_OF_PENNYTREE
    || ' '
    || V_RESULT.RAINBOW_KNIGHT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.PECKLEDON_ID
    || ' '
    || V_RESULT.CRESSEY_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_GREYIRON_OF_ORKMONT;
CREATE OR REPLACE PACKAGE PKG_CRESSEY AS FUNCTION GET_CRESSEY(
  P_ID VARCHAR2
) RETURN VARCHAR2;
PROCEDURE PRINT_CRESSEY(
  P_ID VARCHAR2
);
END PKG_CRESSEY;
CREATE OR REPLACE PACKAGE BODY PKG_CRESSEY AS PROCEDURE PRINT_CRESSEY(
  P_ID VARCHAR2
) AS
  V_RESULT CRESSEY%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    CRESSEY
  WHERE
    CRESSEY.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.OTHOR
    || ' '
    || V_RESULT.LORREN
    || ' '
    || V_RESULT.BELDECAR
    || ' '
    || V_RESULT.HARRY_SAWYER
    || ' '
    || V_RESULT.REYNARD_WEBBER
    || ' '
    || V_RESULT.LYNESSE_HIGHTOWER
    || ' '
    || V_RESULT.SAILORS_WIFE
    || ' '
    || V_RESULT.RICKARD_TYRELL
    || ' '
    || V_RESULT.CLUBFOOT_KARL
    || ' '
    || V_RESULT.KYM
    || ' '
    || V_RESULT.SOREN_SHIELDBREAKER
    || ' '
    || V_RESULT.ARWYN_FREY
    || ' '
    || V_RESULT.ELLARIA_SAND
    || ' '
    || V_RESULT.RHAELLA_TARGARYEN
    || ' '
    || V_RESULT.TYENE_SAND
    || ' '
    || V_RESULT.ROB
    || ' '
    || V_RESULT.LEWYS_PIPER
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.GAUNT_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_CRESSEY(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT CRESSEY%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    CRESSEY
  WHERE
    CRESSEY.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.OTHOR
    || ' '
    || V_RESULT.LORREN
    || ' '
    || V_RESULT.BELDECAR
    || ' '
    || V_RESULT.HARRY_SAWYER
    || ' '
    || V_RESULT.REYNARD_WEBBER
    || ' '
    || V_RESULT.LYNESSE_HIGHTOWER
    || ' '
    || V_RESULT.SAILORS_WIFE
    || ' '
    || V_RESULT.RICKARD_TYRELL
    || ' '
    || V_RESULT.CLUBFOOT_KARL
    || ' '
    || V_RESULT.KYM
    || ' '
    || V_RESULT.SOREN_SHIELDBREAKER
    || ' '
    || V_RESULT.ARWYN_FREY
    || ' '
    || V_RESULT.ELLARIA_SAND
    || ' '
    || V_RESULT.RHAELLA_TARGARYEN
    || ' '
    || V_RESULT.TYENE_SAND
    || ' '
    || V_RESULT.ROB
    || ' '
    || V_RESULT.LEWYS_PIPER
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.GAUNT_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_CRESSEY;
CREATE SEQUENCE SEQ_DAYNE_OF_STARFALL INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_GAUNT INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PECKLEDON INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_GREYIRON_OF_ORKMONT INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CRESSEY INCREMENT BY 1 START WITH 1;