ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER SCHEMA1 IDENTIFIED BY "schema1";

GRANT CONNECT, RESOURCE, CREATE TABLE, DBA TO SCHEMA1;

GRANT CREATE SESSION TO SCHEMA1;

ALTER SESSION SET CURRENT_SCHEMA="SCHEMA1";

CREATE TABLE MERLYN_OF_PEBBLETON (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  ALYS_KARSTARK VARCHAR2(3831),
  MERRELL_FLORENT SMALLINT,
  SKYTE VARCHAR2(748),
  WAYMAR_ROYCE TIMESTAMP,
  DORNISH_DILLY VARCHAR2(748),
  QUENTYN_MARTELL VARCHAR2(3831),
  WENDAMYR CLOB,
  STEFFON_BARATHEON NUMBER,
  ORWYLE VARCHAR2(3831),
  HELMAN_TALLHART DATE,
  HUGH CLOB,
  SLEEPY_JACK VARCHAR2(2800),
  RORO_UHORIS SMALLINT,
  EUSTACE INTEGER,
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  OSGREY_OF_LEAFY_LAKE_ID VARCHAR2(36)
);

CREATE TABLE AMBROSE (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  CERRICK FLOAT,
  MYCAH VARCHAR2(2683),
  AZZAK DATE,
  MERRIT TIMESTAMP,
  LUCOS_CHYTTERING VARCHAR2(748),
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  MERLYN_OF_PEBBLETON_ID VARCHAR2(36),
  NYMEROS_MARTELL_OF_SUNSPEAR_ID VARCHAR2(36)
);

CREATE TABLE OSGREY_OF_LEAFY_LAKE (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  MORD NUMBER,
  EDWYN_FREY VARCHAR2(1526),
  AEGOR_RIVERS NUMBER,
  PYCELLE DATE,
  GOWEN_BARATHEON VARCHAR2(2800),
  GARED VARCHAR2(2800),
  JEYNE_RIVERS DATE,
  RODRIK_FLINT VARCHAR2(1526),
  BELWAS DECIMAL,
  EDRICK_STARK SMALLINT,
  CUTJACK SMALLINT,
  HUBARD_RAMBTON VARCHAR2(748),
  GALT INTEGER,
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  JUSTMAN_ID VARCHAR2(36)
);

CREATE TABLE NYMEROS_MARTELL_OF_SUNSPEAR (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  HELLIWEG VARCHAR2(2683),
  HARLON_BOTLEY VARCHAR2(2800),
  JON_CONNINGTON NUMERIC,
  VYLARR VARCHAR2(2800),
  STIV FLOAT,
  BARSENA_BLACKHAIR VARCHAR2(2683),
  MOELLE VARCHAR2(748),
  RODRIK_FREEBORN FLOAT,
  MIKLAZ DECIMAL,
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  JUSTMAN_ID VARCHAR2(36),
  MERLYN_OF_PEBBLETON_ID VARCHAR2(36),
  OSGREY_OF_LEAFY_LAKE_ID VARCHAR2(36)
);

CREATE TABLE JUSTMAN (
  ID VARCHAR2(36) DEFAULT SYS_GUID(),
  MERALYN CLOB,
  ZOLLO INTEGER,
  CHAYLE CLOB,
  WATTY DATE,
  MANFRYD_YEW SMALLINT,
  QUENTIN_TYRELL VARCHAR2(3831),
  VICTARIA_TYRELL VARCHAR2(2683),
  ALLISER_THORNE VARCHAR2(3831),
  JON_VANCE VARCHAR2(1526),
  SHYRA_ERROL VARCHAR2(748),
  DAGON_GREYJOY VARCHAR2(3831),
  LEYLA_HIGHTOWER VARCHAR2(748),
  WALTON_STARK NUMBER,
  ELWOOD CLOB,
  OLD_HENLY VARCHAR2(748),
  HUMFREY_CLIFTON VARCHAR2(3831),
  MARON_GREYJOY INTEGER,
  AEMON_ESTERMONT DECIMAL,
  JONELLA_CERWYN DATE,
  WILLIT VARCHAR2(2800),
  JEOR_MORMONT VARCHAR2(3831),
  JURNE TIMESTAMP,
  GYLES_III_GARDENER FLOAT,
  NAN TIMESTAMP,
  ARNELD CLOB,
  TYREK_LANNISTER VARCHAR2(748),
  ELDRED_CODD SMALLINT,
  BEREN_TALLHART NUMBER,
  AMEREI_FREY DECIMAL,
  TYBOLT_CRAKEHALL FLOAT,
  BARBA_BRACKEN NUMERIC,
  MARTYN_LANNISTER VARCHAR2(2683),
  ALYSANNE_HIGHTOWER NUMBER,
  ROBIN_HOLLARD INTEGER,
  ADDAM TIMESTAMP,
  BOREMUND_HARLAW CLOB,
  AMBROSE_BUTTERWELL NUMBER,
  OCLEY VARCHAR2(2800),
  EBBEN CLOB,
  JON_ARRYN VARCHAR2(748),
  VYLARR VARCHAR2(2683),
  CLETUS_YRONWOOD VARCHAR2(748),
  KOSS NUMBER,
  WILLAM_DUSTIN VARCHAR2(2683),
  ALYSANE_MORMONT VARCHAR2(748),
  ENGER DATE,
  SMILING_KNIGHT CLOB,
  HARGHAZ INTEGER,
  GWAYNE_CORBRAY DATE,
  ORPHAN_OSS VARCHAR2(748),
  MARWYN_BELMORE VARCHAR2(2800),
  MAYNARD VARCHAR2(2800),
  GARIN VARCHAR2(748),
  ALESTER_NORCROSS NUMERIC,
  PERRA_FREY VARCHAR2(1526),
  GYLORO_DOTHARE VARCHAR2(3831),
  ALLYRIA_DAYNE TIMESTAMP,
  ALYSSA_ARRYN CLOB,
  HENDRY_BRACKEN CLOB,
  ZHOE_BLANETREE NUMBER,
  KRAZZ DATE,
  TRISTIFER_BOTLEY NUMERIC,
  GARRISON_PRESTER FLOAT,
  MORGIL VARCHAR2(2683),
  GENDEL DECIMAL,
  AEGON_III_TARGARYEN DECIMAL,
  COLLIO_QUAYNIS VARCHAR2(1526),
  PUCKENS TIMESTAMP,
  TERRENCE_TOYNE INTEGER,
  HUGH_HAMMER CLOB,
  LUCO_PRESTAYN VARCHAR2(748),
  AEMOND_TARGARYEN FLOAT,
  MARISSA_FREY DATE,
  MATRICE SMALLINT,
  MEHA NUMBER,
  SUMNER_CRAKEHALL NUMERIC,
  CAROLEI_WAYNWOOD INTEGER,
  HARROLD_WESTERLING VARCHAR2(1526),
  MARON_BOTLEY NUMBER,
  CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
  UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
  MERLYN_OF_PEBBLETON_ID VARCHAR2(36),
  AMBROSE_ID VARCHAR2(36)
);

ALTER TABLE MERLYN_OF_PEBBLETON ADD CONSTRAINT MERLYN_OF_PEBBLETON_PK PRIMARY KEY (ID);

ALTER TABLE AMBROSE ADD CONSTRAINT AMBROSE_PK PRIMARY KEY (ID);

ALTER TABLE OSGREY_OF_LEAFY_LAKE ADD CONSTRAINT OSGREY_OF_LEAFY_LAKE_PK PRIMARY KEY (ID);

ALTER TABLE NYMEROS_MARTELL_OF_SUNSPEAR ADD CONSTRAINT NYMEROS_MARTELL_OF_SUNSPEAR_PK PRIMARY KEY (ID);

ALTER TABLE JUSTMAN ADD CONSTRAINT JUSTMAN_PK PRIMARY KEY (ID);

ALTER TABLE MERLYN_OF_PEBBLETON ADD CONSTRAINT MERLYN_OF_PEBBLETON_CK CHECK (QUENTYN_MARTELL IS NOT NULL);

ALTER TABLE AMBROSE ADD CONSTRAINT AMBROSE_CK CHECK (MYCAH IS NOT NULL);

ALTER TABLE OSGREY_OF_LEAFY_LAKE ADD CONSTRAINT OSGREY_OF_LEAFY_LAKE_CK CHECK (GOWEN_BARATHEON IS NOT NULL);

ALTER TABLE NYMEROS_MARTELL_OF_SUNSPEAR ADD CONSTRAINT NYMEROS_MARTELL_OF_SUNSPEAR_CK CHECK (UPDATE_TIME IS NOT NULL);

ALTER TABLE JUSTMAN ADD CONSTRAINT JUSTMAN_CK CHECK (SUMNER_CRAKEHALL IS NOT NULL);

ALTER TABLE MERLYN_OF_PEBBLETON ADD CONSTRAINT MERLYN_OF_PEBBLETON_FK0 FOREIGN KEY (OSGREY_OF_LEAFY_LAKE_ID) REFERENCES OSGREY_OF_LEAFY_LAKE (ID);

ALTER TABLE AMBROSE ADD CONSTRAINT AMBROSE_FK0 FOREIGN KEY (MERLYN_OF_PEBBLETON_ID) REFERENCES MERLYN_OF_PEBBLETON (ID);

ALTER TABLE AMBROSE ADD CONSTRAINT AMBROSE_FK1 FOREIGN KEY (NYMEROS_MARTELL_OF_SUNSPEAR_ID) REFERENCES NYMEROS_MARTELL_OF_SUNSPEAR (ID);

ALTER TABLE OSGREY_OF_LEAFY_LAKE ADD CONSTRAINT OSGREY_OF_LEAFY_LAKE_FK0 FOREIGN KEY (JUSTMAN_ID) REFERENCES JUSTMAN (ID);

ALTER TABLE NYMEROS_MARTELL_OF_SUNSPEAR ADD CONSTRAINT NYMEROS_MARTELL_OF_SUNSPEA_FK0 FOREIGN KEY (JUSTMAN_ID) REFERENCES JUSTMAN (ID);

ALTER TABLE NYMEROS_MARTELL_OF_SUNSPEAR ADD CONSTRAINT NYMEROS_MARTELL_OF_SUNSPEA_FK1 FOREIGN KEY (MERLYN_OF_PEBBLETON_ID) REFERENCES MERLYN_OF_PEBBLETON (ID);

ALTER TABLE NYMEROS_MARTELL_OF_SUNSPEAR ADD CONSTRAINT NYMEROS_MARTELL_OF_SUNSPEA_FK2 FOREIGN KEY (OSGREY_OF_LEAFY_LAKE_ID) REFERENCES OSGREY_OF_LEAFY_LAKE (ID);

ALTER TABLE JUSTMAN ADD CONSTRAINT JUSTMAN_FK0 FOREIGN KEY (MERLYN_OF_PEBBLETON_ID) REFERENCES MERLYN_OF_PEBBLETON (ID);

ALTER TABLE JUSTMAN ADD CONSTRAINT JUSTMAN_FK1 FOREIGN KEY (AMBROSE_ID) REFERENCES AMBROSE (ID);

CREATE OR REPLACE VIEW V_NYMEROS_MARTELL_OF_SUNSPEAR AS
  SELECT
    NYMEROS_MARTELL_OF_SUNSPEAR.JUSTMAN_ID,
    NYMEROS_MARTELL_OF_SUNSPEAR.MERLYN_OF_PEBBLETON_ID,
    NYMEROS_MARTELL_OF_SUNSPEAR.OSGREY_OF_LEAFY_LAKE_ID
  FROM
    NYMEROS_MARTELL_OF_SUNSPEAR
    LEFT JOIN JUSTMAN
    ON NYMEROS_MARTELL_OF_SUNSPEAR.JUSTMAN_ID = JUSTMAN.ID
    LEFT JOIN MERLYN_OF_PEBBLETON
    ON NYMEROS_MARTELL_OF_SUNSPEAR.MERLYN_OF_PEBBLETON_ID = MERLYN_OF_PEBBLETON.ID
    LEFT JOIN OSGREY_OF_LEAFY_LAKE
    ON NYMEROS_MARTELL_OF_SUNSPEAR.OSGREY_OF_LEAFY_LAKE_ID = OSGREY_OF_LEAFY_LAKE.ID;

CREATE OR REPLACE VIEW V_JUSTMAN AS
  SELECT
    JUSTMAN.MERLYN_OF_PEBBLETON_ID,
    JUSTMAN.AMBROSE_ID
  FROM
    JUSTMAN
    LEFT JOIN MERLYN_OF_PEBBLETON
    ON JUSTMAN.MERLYN_OF_PEBBLETON_ID = MERLYN_OF_PEBBLETON.ID
    LEFT JOIN AMBROSE
    ON JUSTMAN.AMBROSE_ID = AMBROSE.ID;

CREATE OR REPLACE VIEW V_AMBROSE AS
  SELECT
    AMBROSE.MERLYN_OF_PEBBLETON_ID,
    AMBROSE.NYMEROS_MARTELL_OF_SUNSPEAR_ID
  FROM
    AMBROSE
    LEFT JOIN MERLYN_OF_PEBBLETON
    ON AMBROSE.MERLYN_OF_PEBBLETON_ID = MERLYN_OF_PEBBLETON.ID
    LEFT JOIN NYMEROS_MARTELL_OF_SUNSPEAR
    ON AMBROSE.NYMEROS_MARTELL_OF_SUNSPEAR_ID = NYMEROS_MARTELL_OF_SUNSPEAR.ID;

CREATE MATERIALIZED VIEW MV_NYMEROS_MARTELL_OF_SUNSPEAR AS
  SELECT
    NYMEROS_MARTELL_OF_SUNSPEAR.JUSTMAN_ID,
    NYMEROS_MARTELL_OF_SUNSPEAR.MERLYN_OF_PEBBLETON_ID,
    NYMEROS_MARTELL_OF_SUNSPEAR.OSGREY_OF_LEAFY_LAKE_ID
  FROM
    NYMEROS_MARTELL_OF_SUNSPEAR
    LEFT JOIN JUSTMAN
    ON NYMEROS_MARTELL_OF_SUNSPEAR.JUSTMAN_ID = JUSTMAN.ID
    LEFT JOIN MERLYN_OF_PEBBLETON
    ON NYMEROS_MARTELL_OF_SUNSPEAR.MERLYN_OF_PEBBLETON_ID = MERLYN_OF_PEBBLETON.ID
    LEFT JOIN OSGREY_OF_LEAFY_LAKE
    ON NYMEROS_MARTELL_OF_SUNSPEAR.OSGREY_OF_LEAFY_LAKE_ID = OSGREY_OF_LEAFY_LAKE.ID;

CREATE MATERIALIZED VIEW MV_JUSTMAN AS
  SELECT
    JUSTMAN.MERLYN_OF_PEBBLETON_ID,
    JUSTMAN.AMBROSE_ID
  FROM
    JUSTMAN
    LEFT JOIN MERLYN_OF_PEBBLETON
    ON JUSTMAN.MERLYN_OF_PEBBLETON_ID = MERLYN_OF_PEBBLETON.ID
    LEFT JOIN AMBROSE
    ON JUSTMAN.AMBROSE_ID = AMBROSE.ID;

CREATE MATERIALIZED VIEW MV_AMBROSE AS
  SELECT
    AMBROSE.MERLYN_OF_PEBBLETON_ID,
    AMBROSE.NYMEROS_MARTELL_OF_SUNSPEAR_ID
  FROM
    AMBROSE
    LEFT JOIN MERLYN_OF_PEBBLETON
    ON AMBROSE.MERLYN_OF_PEBBLETON_ID = MERLYN_OF_PEBBLETON.ID
    LEFT JOIN NYMEROS_MARTELL_OF_SUNSPEAR
    ON AMBROSE.NYMEROS_MARTELL_OF_SUNSPEAR_ID = NYMEROS_MARTELL_OF_SUNSPEAR.ID;

CREATE OR REPLACE PROCEDURE PRINT_MERLYN_OF_PEBBLETON(
  P_ID VARCHAR2
) AS
  V_RESULT MERLYN_OF_PEBBLETON%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    MERLYN_OF_PEBBLETON
  WHERE
    MERLYN_OF_PEBBLETON.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ALYS_KARSTARK
    || ' '
    || V_RESULT.MERRELL_FLORENT
    || ' '
    || V_RESULT.SKYTE
    || ' '
    || V_RESULT.WAYMAR_ROYCE
    || ' '
    || V_RESULT.DORNISH_DILLY
    || ' '
    || V_RESULT.QUENTYN_MARTELL
    || ' '
    || V_RESULT.WENDAMYR
    || ' '
    || V_RESULT.STEFFON_BARATHEON
    || ' '
    || V_RESULT.ORWYLE
    || ' '
    || V_RESULT.HELMAN_TALLHART
    || ' '
    || V_RESULT.HUGH
    || ' '
    || V_RESULT.SLEEPY_JACK
    || ' '
    || V_RESULT.RORO_UHORIS
    || ' '
    || V_RESULT.EUSTACE
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.OSGREY_OF_LEAFY_LAKE_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PRINT_AMBROSE(
  P_ID VARCHAR2
) AS
  V_RESULT AMBROSE%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    AMBROSE
  WHERE
    AMBROSE.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.CERRICK
    || ' '
    || V_RESULT.MYCAH
    || ' '
    || V_RESULT.AZZAK
    || ' '
    || V_RESULT.MERRIT
    || ' '
    || V_RESULT.LUCOS_CHYTTERING
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.NYMEROS_MARTELL_OF_SUNSPEAR_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PRINT_OSGREY_OF_LEAFY_LAKE(
  P_ID VARCHAR2
) AS
  V_RESULT OSGREY_OF_LEAFY_LAKE%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    OSGREY_OF_LEAFY_LAKE
  WHERE
    OSGREY_OF_LEAFY_LAKE.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MORD
    || ' '
    || V_RESULT.EDWYN_FREY
    || ' '
    || V_RESULT.AEGOR_RIVERS
    || ' '
    || V_RESULT.PYCELLE
    || ' '
    || V_RESULT.GOWEN_BARATHEON
    || ' '
    || V_RESULT.GARED
    || ' '
    || V_RESULT.JEYNE_RIVERS
    || ' '
    || V_RESULT.RODRIK_FLINT
    || ' '
    || V_RESULT.BELWAS
    || ' '
    || V_RESULT.EDRICK_STARK
    || ' '
    || V_RESULT.CUTJACK
    || ' '
    || V_RESULT.HUBARD_RAMBTON
    || ' '
    || V_RESULT.GALT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.JUSTMAN_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PRINT_NYMEROS_MARTELL_OF_SUNSPEAR(
  P_ID VARCHAR2
) AS
  V_RESULT NYMEROS_MARTELL_OF_SUNSPEAR%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    NYMEROS_MARTELL_OF_SUNSPEAR
  WHERE
    NYMEROS_MARTELL_OF_SUNSPEAR.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.HELLIWEG
    || ' '
    || V_RESULT.HARLON_BOTLEY
    || ' '
    || V_RESULT.JON_CONNINGTON
    || ' '
    || V_RESULT.VYLARR
    || ' '
    || V_RESULT.STIV
    || ' '
    || V_RESULT.BARSENA_BLACKHAIR
    || ' '
    || V_RESULT.MOELLE
    || ' '
    || V_RESULT.RODRIK_FREEBORN
    || ' '
    || V_RESULT.MIKLAZ
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.JUSTMAN_ID
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.OSGREY_OF_LEAFY_LAKE_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PRINT_JUSTMAN(
  P_ID VARCHAR2
) AS
  V_RESULT JUSTMAN%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    JUSTMAN
  WHERE
    JUSTMAN.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MERALYN
    || ' '
    || V_RESULT.ZOLLO
    || ' '
    || V_RESULT.CHAYLE
    || ' '
    || V_RESULT.WATTY
    || ' '
    || V_RESULT.MANFRYD_YEW
    || ' '
    || V_RESULT.QUENTIN_TYRELL
    || ' '
    || V_RESULT.VICTARIA_TYRELL
    || ' '
    || V_RESULT.ALLISER_THORNE
    || ' '
    || V_RESULT.JON_VANCE
    || ' '
    || V_RESULT.SHYRA_ERROL
    || ' '
    || V_RESULT.DAGON_GREYJOY
    || ' '
    || V_RESULT.LEYLA_HIGHTOWER
    || ' '
    || V_RESULT.WALTON_STARK
    || ' '
    || V_RESULT.ELWOOD
    || ' '
    || V_RESULT.OLD_HENLY
    || ' '
    || V_RESULT.HUMFREY_CLIFTON
    || ' '
    || V_RESULT.MARON_GREYJOY
    || ' '
    || V_RESULT.AEMON_ESTERMONT
    || ' '
    || V_RESULT.JONELLA_CERWYN
    || ' '
    || V_RESULT.WILLIT
    || ' '
    || V_RESULT.JEOR_MORMONT
    || ' '
    || V_RESULT.JURNE
    || ' '
    || V_RESULT.GYLES_III_GARDENER
    || ' '
    || V_RESULT.NAN
    || ' '
    || V_RESULT.ARNELD
    || ' '
    || V_RESULT.TYREK_LANNISTER
    || ' '
    || V_RESULT.ELDRED_CODD
    || ' '
    || V_RESULT.BEREN_TALLHART
    || ' '
    || V_RESULT.AMEREI_FREY
    || ' '
    || V_RESULT.TYBOLT_CRAKEHALL
    || ' '
    || V_RESULT.BARBA_BRACKEN
    || ' '
    || V_RESULT.MARTYN_LANNISTER
    || ' '
    || V_RESULT.ALYSANNE_HIGHTOWER
    || ' '
    || V_RESULT.ROBIN_HOLLARD
    || ' '
    || V_RESULT.ADDAM
    || ' '
    || V_RESULT.BOREMUND_HARLAW
    || ' '
    || V_RESULT.AMBROSE_BUTTERWELL
    || ' '
    || V_RESULT.OCLEY
    || ' '
    || V_RESULT.EBBEN
    || ' '
    || V_RESULT.JON_ARRYN
    || ' '
    || V_RESULT.VYLARR
    || ' '
    || V_RESULT.CLETUS_YRONWOOD
    || ' '
    || V_RESULT.KOSS
    || ' '
    || V_RESULT.WILLAM_DUSTIN
    || ' '
    || V_RESULT.ALYSANE_MORMONT
    || ' '
    || V_RESULT.ENGER
    || ' '
    || V_RESULT.SMILING_KNIGHT
    || ' '
    || V_RESULT.HARGHAZ
    || ' '
    || V_RESULT.GWAYNE_CORBRAY
    || ' '
    || V_RESULT.ORPHAN_OSS
    || ' '
    || V_RESULT.MARWYN_BELMORE
    || ' '
    || V_RESULT.MAYNARD
    || ' '
    || V_RESULT.GARIN
    || ' '
    || V_RESULT.ALESTER_NORCROSS
    || ' '
    || V_RESULT.PERRA_FREY
    || ' '
    || V_RESULT.GYLORO_DOTHARE
    || ' '
    || V_RESULT.ALLYRIA_DAYNE
    || ' '
    || V_RESULT.ALYSSA_ARRYN
    || ' '
    || V_RESULT.HENDRY_BRACKEN
    || ' '
    || V_RESULT.ZHOE_BLANETREE
    || ' '
    || V_RESULT.KRAZZ
    || ' '
    || V_RESULT.TRISTIFER_BOTLEY
    || ' '
    || V_RESULT.GARRISON_PRESTER
    || ' '
    || V_RESULT.MORGIL
    || ' '
    || V_RESULT.GENDEL
    || ' '
    || V_RESULT.AEGON_III_TARGARYEN
    || ' '
    || V_RESULT.COLLIO_QUAYNIS
    || ' '
    || V_RESULT.PUCKENS
    || ' '
    || V_RESULT.TERRENCE_TOYNE
    || ' '
    || V_RESULT.HUGH_HAMMER
    || ' '
    || V_RESULT.LUCO_PRESTAYN
    || ' '
    || V_RESULT.AEMOND_TARGARYEN
    || ' '
    || V_RESULT.MARISSA_FREY
    || ' '
    || V_RESULT.MATRICE
    || ' '
    || V_RESULT.MEHA
    || ' '
    || V_RESULT.SUMNER_CRAKEHALL
    || ' '
    || V_RESULT.CAROLEI_WAYNWOOD
    || ' '
    || V_RESULT.HARROLD_WESTERLING
    || ' '
    || V_RESULT.MARON_BOTLEY
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.AMBROSE_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

CREATE OR REPLACE FUNCTION GET_MERLYN_OF_PEBBLETON(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT MERLYN_OF_PEBBLETON%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    MERLYN_OF_PEBBLETON
  WHERE
    MERLYN_OF_PEBBLETON.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ALYS_KARSTARK
    || ' '
    || V_RESULT.MERRELL_FLORENT
    || ' '
    || V_RESULT.SKYTE
    || ' '
    || V_RESULT.WAYMAR_ROYCE
    || ' '
    || V_RESULT.DORNISH_DILLY
    || ' '
    || V_RESULT.QUENTYN_MARTELL
    || ' '
    || V_RESULT.WENDAMYR
    || ' '
    || V_RESULT.STEFFON_BARATHEON
    || ' '
    || V_RESULT.ORWYLE
    || ' '
    || V_RESULT.HELMAN_TALLHART
    || ' '
    || V_RESULT.HUGH
    || ' '
    || V_RESULT.SLEEPY_JACK
    || ' '
    || V_RESULT.RORO_UHORIS
    || ' '
    || V_RESULT.EUSTACE
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.OSGREY_OF_LEAFY_LAKE_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GET_AMBROSE(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT AMBROSE%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    AMBROSE
  WHERE
    AMBROSE.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.CERRICK
    || ' '
    || V_RESULT.MYCAH
    || ' '
    || V_RESULT.AZZAK
    || ' '
    || V_RESULT.MERRIT
    || ' '
    || V_RESULT.LUCOS_CHYTTERING
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.NYMEROS_MARTELL_OF_SUNSPEAR_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GET_OSGREY_OF_LEAFY_LAKE(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT OSGREY_OF_LEAFY_LAKE%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    OSGREY_OF_LEAFY_LAKE
  WHERE
    OSGREY_OF_LEAFY_LAKE.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MORD
    || ' '
    || V_RESULT.EDWYN_FREY
    || ' '
    || V_RESULT.AEGOR_RIVERS
    || ' '
    || V_RESULT.PYCELLE
    || ' '
    || V_RESULT.GOWEN_BARATHEON
    || ' '
    || V_RESULT.GARED
    || ' '
    || V_RESULT.JEYNE_RIVERS
    || ' '
    || V_RESULT.RODRIK_FLINT
    || ' '
    || V_RESULT.BELWAS
    || ' '
    || V_RESULT.EDRICK_STARK
    || ' '
    || V_RESULT.CUTJACK
    || ' '
    || V_RESULT.HUBARD_RAMBTON
    || ' '
    || V_RESULT.GALT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.JUSTMAN_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GET_NYMEROS_MARTELL_OF_SUNSPEAR(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT NYMEROS_MARTELL_OF_SUNSPEAR%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    NYMEROS_MARTELL_OF_SUNSPEAR
  WHERE
    NYMEROS_MARTELL_OF_SUNSPEAR.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.HELLIWEG
    || ' '
    || V_RESULT.HARLON_BOTLEY
    || ' '
    || V_RESULT.JON_CONNINGTON
    || ' '
    || V_RESULT.VYLARR
    || ' '
    || V_RESULT.STIV
    || ' '
    || V_RESULT.BARSENA_BLACKHAIR
    || ' '
    || V_RESULT.MOELLE
    || ' '
    || V_RESULT.RODRIK_FREEBORN
    || ' '
    || V_RESULT.MIKLAZ
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.JUSTMAN_ID
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.OSGREY_OF_LEAFY_LAKE_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GET_JUSTMAN(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT JUSTMAN%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    JUSTMAN
  WHERE
    JUSTMAN.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MERALYN
    || ' '
    || V_RESULT.ZOLLO
    || ' '
    || V_RESULT.CHAYLE
    || ' '
    || V_RESULT.WATTY
    || ' '
    || V_RESULT.MANFRYD_YEW
    || ' '
    || V_RESULT.QUENTIN_TYRELL
    || ' '
    || V_RESULT.VICTARIA_TYRELL
    || ' '
    || V_RESULT.ALLISER_THORNE
    || ' '
    || V_RESULT.JON_VANCE
    || ' '
    || V_RESULT.SHYRA_ERROL
    || ' '
    || V_RESULT.DAGON_GREYJOY
    || ' '
    || V_RESULT.LEYLA_HIGHTOWER
    || ' '
    || V_RESULT.WALTON_STARK
    || ' '
    || V_RESULT.ELWOOD
    || ' '
    || V_RESULT.OLD_HENLY
    || ' '
    || V_RESULT.HUMFREY_CLIFTON
    || ' '
    || V_RESULT.MARON_GREYJOY
    || ' '
    || V_RESULT.AEMON_ESTERMONT
    || ' '
    || V_RESULT.JONELLA_CERWYN
    || ' '
    || V_RESULT.WILLIT
    || ' '
    || V_RESULT.JEOR_MORMONT
    || ' '
    || V_RESULT.JURNE
    || ' '
    || V_RESULT.GYLES_III_GARDENER
    || ' '
    || V_RESULT.NAN
    || ' '
    || V_RESULT.ARNELD
    || ' '
    || V_RESULT.TYREK_LANNISTER
    || ' '
    || V_RESULT.ELDRED_CODD
    || ' '
    || V_RESULT.BEREN_TALLHART
    || ' '
    || V_RESULT.AMEREI_FREY
    || ' '
    || V_RESULT.TYBOLT_CRAKEHALL
    || ' '
    || V_RESULT.BARBA_BRACKEN
    || ' '
    || V_RESULT.MARTYN_LANNISTER
    || ' '
    || V_RESULT.ALYSANNE_HIGHTOWER
    || ' '
    || V_RESULT.ROBIN_HOLLARD
    || ' '
    || V_RESULT.ADDAM
    || ' '
    || V_RESULT.BOREMUND_HARLAW
    || ' '
    || V_RESULT.AMBROSE_BUTTERWELL
    || ' '
    || V_RESULT.OCLEY
    || ' '
    || V_RESULT.EBBEN
    || ' '
    || V_RESULT.JON_ARRYN
    || ' '
    || V_RESULT.VYLARR
    || ' '
    || V_RESULT.CLETUS_YRONWOOD
    || ' '
    || V_RESULT.KOSS
    || ' '
    || V_RESULT.WILLAM_DUSTIN
    || ' '
    || V_RESULT.ALYSANE_MORMONT
    || ' '
    || V_RESULT.ENGER
    || ' '
    || V_RESULT.SMILING_KNIGHT
    || ' '
    || V_RESULT.HARGHAZ
    || ' '
    || V_RESULT.GWAYNE_CORBRAY
    || ' '
    || V_RESULT.ORPHAN_OSS
    || ' '
    || V_RESULT.MARWYN_BELMORE
    || ' '
    || V_RESULT.MAYNARD
    || ' '
    || V_RESULT.GARIN
    || ' '
    || V_RESULT.ALESTER_NORCROSS
    || ' '
    || V_RESULT.PERRA_FREY
    || ' '
    || V_RESULT.GYLORO_DOTHARE
    || ' '
    || V_RESULT.ALLYRIA_DAYNE
    || ' '
    || V_RESULT.ALYSSA_ARRYN
    || ' '
    || V_RESULT.HENDRY_BRACKEN
    || ' '
    || V_RESULT.ZHOE_BLANETREE
    || ' '
    || V_RESULT.KRAZZ
    || ' '
    || V_RESULT.TRISTIFER_BOTLEY
    || ' '
    || V_RESULT.GARRISON_PRESTER
    || ' '
    || V_RESULT.MORGIL
    || ' '
    || V_RESULT.GENDEL
    || ' '
    || V_RESULT.AEGON_III_TARGARYEN
    || ' '
    || V_RESULT.COLLIO_QUAYNIS
    || ' '
    || V_RESULT.PUCKENS
    || ' '
    || V_RESULT.TERRENCE_TOYNE
    || ' '
    || V_RESULT.HUGH_HAMMER
    || ' '
    || V_RESULT.LUCO_PRESTAYN
    || ' '
    || V_RESULT.AEMOND_TARGARYEN
    || ' '
    || V_RESULT.MARISSA_FREY
    || ' '
    || V_RESULT.MATRICE
    || ' '
    || V_RESULT.MEHA
    || ' '
    || V_RESULT.SUMNER_CRAKEHALL
    || ' '
    || V_RESULT.CAROLEI_WAYNWOOD
    || ' '
    || V_RESULT.HARROLD_WESTERLING
    || ' '
    || V_RESULT.MARON_BOTLEY
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.AMBROSE_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
/

CREATE OR REPLACE PACKAGE PKG_MERLYN_OF_PEBBLETON AS
  FUNCTION GET_MERLYN_OF_PEBBLETON(
    P_ID VARCHAR2
  ) RETURN VARCHAR2;
  PROCEDURE PRINT_MERLYN_OF_PEBBLETON(
    P_ID VARCHAR2
  );
END PKG_MERLYN_OF_PEBBLETON;
CREATE OR REPLACE PACKAGE BODY PKG_MERLYN_OF_PEBBLETON AS PROCEDURE PRINT_MERLYN_OF_PEBBLETON(
  P_ID VARCHAR2
) AS
  V_RESULT MERLYN_OF_PEBBLETON%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    MERLYN_OF_PEBBLETON
  WHERE
    MERLYN_OF_PEBBLETON.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ALYS_KARSTARK
    || ' '
    || V_RESULT.MERRELL_FLORENT
    || ' '
    || V_RESULT.SKYTE
    || ' '
    || V_RESULT.WAYMAR_ROYCE
    || ' '
    || V_RESULT.DORNISH_DILLY
    || ' '
    || V_RESULT.QUENTYN_MARTELL
    || ' '
    || V_RESULT.WENDAMYR
    || ' '
    || V_RESULT.STEFFON_BARATHEON
    || ' '
    || V_RESULT.ORWYLE
    || ' '
    || V_RESULT.HELMAN_TALLHART
    || ' '
    || V_RESULT.HUGH
    || ' '
    || V_RESULT.SLEEPY_JACK
    || ' '
    || V_RESULT.RORO_UHORIS
    || ' '
    || V_RESULT.EUSTACE
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.OSGREY_OF_LEAFY_LAKE_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_MERLYN_OF_PEBBLETON(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT MERLYN_OF_PEBBLETON%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    MERLYN_OF_PEBBLETON
  WHERE
    MERLYN_OF_PEBBLETON.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.ALYS_KARSTARK
    || ' '
    || V_RESULT.MERRELL_FLORENT
    || ' '
    || V_RESULT.SKYTE
    || ' '
    || V_RESULT.WAYMAR_ROYCE
    || ' '
    || V_RESULT.DORNISH_DILLY
    || ' '
    || V_RESULT.QUENTYN_MARTELL
    || ' '
    || V_RESULT.WENDAMYR
    || ' '
    || V_RESULT.STEFFON_BARATHEON
    || ' '
    || V_RESULT.ORWYLE
    || ' '
    || V_RESULT.HELMAN_TALLHART
    || ' '
    || V_RESULT.HUGH
    || ' '
    || V_RESULT.SLEEPY_JACK
    || ' '
    || V_RESULT.RORO_UHORIS
    || ' '
    || V_RESULT.EUSTACE
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.OSGREY_OF_LEAFY_LAKE_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_MERLYN_OF_PEBBLETON;
CREATE OR REPLACE PACKAGE PKG_AMBROSE AS FUNCTION GET_AMBROSE(
  P_ID VARCHAR2
) RETURN VARCHAR2;
PROCEDURE PRINT_AMBROSE(
  P_ID VARCHAR2
);
END PKG_AMBROSE;
CREATE OR REPLACE PACKAGE BODY PKG_AMBROSE AS PROCEDURE PRINT_AMBROSE(
  P_ID VARCHAR2
) AS
  V_RESULT AMBROSE%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    AMBROSE
  WHERE
    AMBROSE.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.CERRICK
    || ' '
    || V_RESULT.MYCAH
    || ' '
    || V_RESULT.AZZAK
    || ' '
    || V_RESULT.MERRIT
    || ' '
    || V_RESULT.LUCOS_CHYTTERING
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.NYMEROS_MARTELL_OF_SUNSPEAR_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_AMBROSE(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT AMBROSE%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    AMBROSE
  WHERE
    AMBROSE.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.CERRICK
    || ' '
    || V_RESULT.MYCAH
    || ' '
    || V_RESULT.AZZAK
    || ' '
    || V_RESULT.MERRIT
    || ' '
    || V_RESULT.LUCOS_CHYTTERING
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.NYMEROS_MARTELL_OF_SUNSPEAR_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_AMBROSE;
CREATE OR REPLACE PACKAGE PKG_OSGREY_OF_LEAFY_LAKE AS FUNCTION GET_OSGREY_OF_LEAFY_LAKE(
  P_ID VARCHAR2
) RETURN VARCHAR2;
PROCEDURE PRINT_OSGREY_OF_LEAFY_LAKE(
  P_ID VARCHAR2
);
END PKG_OSGREY_OF_LEAFY_LAKE;
CREATE OR REPLACE PACKAGE BODY PKG_OSGREY_OF_LEAFY_LAKE AS PROCEDURE PRINT_OSGREY_OF_LEAFY_LAKE(
  P_ID VARCHAR2
) AS
  V_RESULT OSGREY_OF_LEAFY_LAKE%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    OSGREY_OF_LEAFY_LAKE
  WHERE
    OSGREY_OF_LEAFY_LAKE.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MORD
    || ' '
    || V_RESULT.EDWYN_FREY
    || ' '
    || V_RESULT.AEGOR_RIVERS
    || ' '
    || V_RESULT.PYCELLE
    || ' '
    || V_RESULT.GOWEN_BARATHEON
    || ' '
    || V_RESULT.GARED
    || ' '
    || V_RESULT.JEYNE_RIVERS
    || ' '
    || V_RESULT.RODRIK_FLINT
    || ' '
    || V_RESULT.BELWAS
    || ' '
    || V_RESULT.EDRICK_STARK
    || ' '
    || V_RESULT.CUTJACK
    || ' '
    || V_RESULT.HUBARD_RAMBTON
    || ' '
    || V_RESULT.GALT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.JUSTMAN_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_OSGREY_OF_LEAFY_LAKE(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT OSGREY_OF_LEAFY_LAKE%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    OSGREY_OF_LEAFY_LAKE
  WHERE
    OSGREY_OF_LEAFY_LAKE.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MORD
    || ' '
    || V_RESULT.EDWYN_FREY
    || ' '
    || V_RESULT.AEGOR_RIVERS
    || ' '
    || V_RESULT.PYCELLE
    || ' '
    || V_RESULT.GOWEN_BARATHEON
    || ' '
    || V_RESULT.GARED
    || ' '
    || V_RESULT.JEYNE_RIVERS
    || ' '
    || V_RESULT.RODRIK_FLINT
    || ' '
    || V_RESULT.BELWAS
    || ' '
    || V_RESULT.EDRICK_STARK
    || ' '
    || V_RESULT.CUTJACK
    || ' '
    || V_RESULT.HUBARD_RAMBTON
    || ' '
    || V_RESULT.GALT
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.JUSTMAN_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_OSGREY_OF_LEAFY_LAKE;
CREATE OR REPLACE PACKAGE PKG_NYMEROS_MARTELL_OF_SUNSPEAR AS FUNCTION GET_NYMEROS_MARTELL_OF_SUNSPEAR(
  P_ID VARCHAR2
) RETURN VARCHAR2;
PROCEDURE PRINT_NYMEROS_MARTELL_OF_SUNSPEAR(
  P_ID VARCHAR2
);
END PKG_NYMEROS_MARTELL_OF_SUNSPEAR;
CREATE OR REPLACE PACKAGE BODY PKG_NYMEROS_MARTELL_OF_SUNSPEAR AS PROCEDURE PRINT_NYMEROS_MARTELL_OF_SUNSPEAR(
  P_ID VARCHAR2
) AS
  V_RESULT NYMEROS_MARTELL_OF_SUNSPEAR%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    NYMEROS_MARTELL_OF_SUNSPEAR
  WHERE
    NYMEROS_MARTELL_OF_SUNSPEAR.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.HELLIWEG
    || ' '
    || V_RESULT.HARLON_BOTLEY
    || ' '
    || V_RESULT.JON_CONNINGTON
    || ' '
    || V_RESULT.VYLARR
    || ' '
    || V_RESULT.STIV
    || ' '
    || V_RESULT.BARSENA_BLACKHAIR
    || ' '
    || V_RESULT.MOELLE
    || ' '
    || V_RESULT.RODRIK_FREEBORN
    || ' '
    || V_RESULT.MIKLAZ
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.JUSTMAN_ID
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.OSGREY_OF_LEAFY_LAKE_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_NYMEROS_MARTELL_OF_SUNSPEAR(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT NYMEROS_MARTELL_OF_SUNSPEAR%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    NYMEROS_MARTELL_OF_SUNSPEAR
  WHERE
    NYMEROS_MARTELL_OF_SUNSPEAR.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.HELLIWEG
    || ' '
    || V_RESULT.HARLON_BOTLEY
    || ' '
    || V_RESULT.JON_CONNINGTON
    || ' '
    || V_RESULT.VYLARR
    || ' '
    || V_RESULT.STIV
    || ' '
    || V_RESULT.BARSENA_BLACKHAIR
    || ' '
    || V_RESULT.MOELLE
    || ' '
    || V_RESULT.RODRIK_FREEBORN
    || ' '
    || V_RESULT.MIKLAZ
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.JUSTMAN_ID
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.OSGREY_OF_LEAFY_LAKE_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_NYMEROS_MARTELL_OF_SUNSPEAR;
CREATE OR REPLACE PACKAGE PKG_JUSTMAN AS FUNCTION GET_JUSTMAN(
  P_ID VARCHAR2
) RETURN VARCHAR2;
PROCEDURE PRINT_JUSTMAN(
  P_ID VARCHAR2
);
END PKG_JUSTMAN;
CREATE OR REPLACE PACKAGE BODY PKG_JUSTMAN AS PROCEDURE PRINT_JUSTMAN(
  P_ID VARCHAR2
) AS
  V_RESULT JUSTMAN%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    JUSTMAN
  WHERE
    JUSTMAN.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MERALYN
    || ' '
    || V_RESULT.ZOLLO
    || ' '
    || V_RESULT.CHAYLE
    || ' '
    || V_RESULT.WATTY
    || ' '
    || V_RESULT.MANFRYD_YEW
    || ' '
    || V_RESULT.QUENTIN_TYRELL
    || ' '
    || V_RESULT.VICTARIA_TYRELL
    || ' '
    || V_RESULT.ALLISER_THORNE
    || ' '
    || V_RESULT.JON_VANCE
    || ' '
    || V_RESULT.SHYRA_ERROL
    || ' '
    || V_RESULT.DAGON_GREYJOY
    || ' '
    || V_RESULT.LEYLA_HIGHTOWER
    || ' '
    || V_RESULT.WALTON_STARK
    || ' '
    || V_RESULT.ELWOOD
    || ' '
    || V_RESULT.OLD_HENLY
    || ' '
    || V_RESULT.HUMFREY_CLIFTON
    || ' '
    || V_RESULT.MARON_GREYJOY
    || ' '
    || V_RESULT.AEMON_ESTERMONT
    || ' '
    || V_RESULT.JONELLA_CERWYN
    || ' '
    || V_RESULT.WILLIT
    || ' '
    || V_RESULT.JEOR_MORMONT
    || ' '
    || V_RESULT.JURNE
    || ' '
    || V_RESULT.GYLES_III_GARDENER
    || ' '
    || V_RESULT.NAN
    || ' '
    || V_RESULT.ARNELD
    || ' '
    || V_RESULT.TYREK_LANNISTER
    || ' '
    || V_RESULT.ELDRED_CODD
    || ' '
    || V_RESULT.BEREN_TALLHART
    || ' '
    || V_RESULT.AMEREI_FREY
    || ' '
    || V_RESULT.TYBOLT_CRAKEHALL
    || ' '
    || V_RESULT.BARBA_BRACKEN
    || ' '
    || V_RESULT.MARTYN_LANNISTER
    || ' '
    || V_RESULT.ALYSANNE_HIGHTOWER
    || ' '
    || V_RESULT.ROBIN_HOLLARD
    || ' '
    || V_RESULT.ADDAM
    || ' '
    || V_RESULT.BOREMUND_HARLAW
    || ' '
    || V_RESULT.AMBROSE_BUTTERWELL
    || ' '
    || V_RESULT.OCLEY
    || ' '
    || V_RESULT.EBBEN
    || ' '
    || V_RESULT.JON_ARRYN
    || ' '
    || V_RESULT.VYLARR
    || ' '
    || V_RESULT.CLETUS_YRONWOOD
    || ' '
    || V_RESULT.KOSS
    || ' '
    || V_RESULT.WILLAM_DUSTIN
    || ' '
    || V_RESULT.ALYSANE_MORMONT
    || ' '
    || V_RESULT.ENGER
    || ' '
    || V_RESULT.SMILING_KNIGHT
    || ' '
    || V_RESULT.HARGHAZ
    || ' '
    || V_RESULT.GWAYNE_CORBRAY
    || ' '
    || V_RESULT.ORPHAN_OSS
    || ' '
    || V_RESULT.MARWYN_BELMORE
    || ' '
    || V_RESULT.MAYNARD
    || ' '
    || V_RESULT.GARIN
    || ' '
    || V_RESULT.ALESTER_NORCROSS
    || ' '
    || V_RESULT.PERRA_FREY
    || ' '
    || V_RESULT.GYLORO_DOTHARE
    || ' '
    || V_RESULT.ALLYRIA_DAYNE
    || ' '
    || V_RESULT.ALYSSA_ARRYN
    || ' '
    || V_RESULT.HENDRY_BRACKEN
    || ' '
    || V_RESULT.ZHOE_BLANETREE
    || ' '
    || V_RESULT.KRAZZ
    || ' '
    || V_RESULT.TRISTIFER_BOTLEY
    || ' '
    || V_RESULT.GARRISON_PRESTER
    || ' '
    || V_RESULT.MORGIL
    || ' '
    || V_RESULT.GENDEL
    || ' '
    || V_RESULT.AEGON_III_TARGARYEN
    || ' '
    || V_RESULT.COLLIO_QUAYNIS
    || ' '
    || V_RESULT.PUCKENS
    || ' '
    || V_RESULT.TERRENCE_TOYNE
    || ' '
    || V_RESULT.HUGH_HAMMER
    || ' '
    || V_RESULT.LUCO_PRESTAYN
    || ' '
    || V_RESULT.AEMOND_TARGARYEN
    || ' '
    || V_RESULT.MARISSA_FREY
    || ' '
    || V_RESULT.MATRICE
    || ' '
    || V_RESULT.MEHA
    || ' '
    || V_RESULT.SUMNER_CRAKEHALL
    || ' '
    || V_RESULT.CAROLEI_WAYNWOOD
    || ' '
    || V_RESULT.HARROLD_WESTERLING
    || ' '
    || V_RESULT.MARON_BOTLEY
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.AMBROSE_ID );
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
FUNCTION GET_JUSTMAN(
  P_ID VARCHAR2
) RETURN VARCHAR2 IS
  V_RESULT JUSTMAN%ROWTYPE;
BEGIN
  SELECT
    * INTO V_RESULT
  FROM
    JUSTMAN
  WHERE
    JUSTMAN.ID = P_ID;
  DBMS_OUTPUT.PUT_LINE( V_RESULT.ID
    || ' '
    || V_RESULT.MERALYN
    || ' '
    || V_RESULT.ZOLLO
    || ' '
    || V_RESULT.CHAYLE
    || ' '
    || V_RESULT.WATTY
    || ' '
    || V_RESULT.MANFRYD_YEW
    || ' '
    || V_RESULT.QUENTIN_TYRELL
    || ' '
    || V_RESULT.VICTARIA_TYRELL
    || ' '
    || V_RESULT.ALLISER_THORNE
    || ' '
    || V_RESULT.JON_VANCE
    || ' '
    || V_RESULT.SHYRA_ERROL
    || ' '
    || V_RESULT.DAGON_GREYJOY
    || ' '
    || V_RESULT.LEYLA_HIGHTOWER
    || ' '
    || V_RESULT.WALTON_STARK
    || ' '
    || V_RESULT.ELWOOD
    || ' '
    || V_RESULT.OLD_HENLY
    || ' '
    || V_RESULT.HUMFREY_CLIFTON
    || ' '
    || V_RESULT.MARON_GREYJOY
    || ' '
    || V_RESULT.AEMON_ESTERMONT
    || ' '
    || V_RESULT.JONELLA_CERWYN
    || ' '
    || V_RESULT.WILLIT
    || ' '
    || V_RESULT.JEOR_MORMONT
    || ' '
    || V_RESULT.JURNE
    || ' '
    || V_RESULT.GYLES_III_GARDENER
    || ' '
    || V_RESULT.NAN
    || ' '
    || V_RESULT.ARNELD
    || ' '
    || V_RESULT.TYREK_LANNISTER
    || ' '
    || V_RESULT.ELDRED_CODD
    || ' '
    || V_RESULT.BEREN_TALLHART
    || ' '
    || V_RESULT.AMEREI_FREY
    || ' '
    || V_RESULT.TYBOLT_CRAKEHALL
    || ' '
    || V_RESULT.BARBA_BRACKEN
    || ' '
    || V_RESULT.MARTYN_LANNISTER
    || ' '
    || V_RESULT.ALYSANNE_HIGHTOWER
    || ' '
    || V_RESULT.ROBIN_HOLLARD
    || ' '
    || V_RESULT.ADDAM
    || ' '
    || V_RESULT.BOREMUND_HARLAW
    || ' '
    || V_RESULT.AMBROSE_BUTTERWELL
    || ' '
    || V_RESULT.OCLEY
    || ' '
    || V_RESULT.EBBEN
    || ' '
    || V_RESULT.JON_ARRYN
    || ' '
    || V_RESULT.VYLARR
    || ' '
    || V_RESULT.CLETUS_YRONWOOD
    || ' '
    || V_RESULT.KOSS
    || ' '
    || V_RESULT.WILLAM_DUSTIN
    || ' '
    || V_RESULT.ALYSANE_MORMONT
    || ' '
    || V_RESULT.ENGER
    || ' '
    || V_RESULT.SMILING_KNIGHT
    || ' '
    || V_RESULT.HARGHAZ
    || ' '
    || V_RESULT.GWAYNE_CORBRAY
    || ' '
    || V_RESULT.ORPHAN_OSS
    || ' '
    || V_RESULT.MARWYN_BELMORE
    || ' '
    || V_RESULT.MAYNARD
    || ' '
    || V_RESULT.GARIN
    || ' '
    || V_RESULT.ALESTER_NORCROSS
    || ' '
    || V_RESULT.PERRA_FREY
    || ' '
    || V_RESULT.GYLORO_DOTHARE
    || ' '
    || V_RESULT.ALLYRIA_DAYNE
    || ' '
    || V_RESULT.ALYSSA_ARRYN
    || ' '
    || V_RESULT.HENDRY_BRACKEN
    || ' '
    || V_RESULT.ZHOE_BLANETREE
    || ' '
    || V_RESULT.KRAZZ
    || ' '
    || V_RESULT.TRISTIFER_BOTLEY
    || ' '
    || V_RESULT.GARRISON_PRESTER
    || ' '
    || V_RESULT.MORGIL
    || ' '
    || V_RESULT.GENDEL
    || ' '
    || V_RESULT.AEGON_III_TARGARYEN
    || ' '
    || V_RESULT.COLLIO_QUAYNIS
    || ' '
    || V_RESULT.PUCKENS
    || ' '
    || V_RESULT.TERRENCE_TOYNE
    || ' '
    || V_RESULT.HUGH_HAMMER
    || ' '
    || V_RESULT.LUCO_PRESTAYN
    || ' '
    || V_RESULT.AEMOND_TARGARYEN
    || ' '
    || V_RESULT.MARISSA_FREY
    || ' '
    || V_RESULT.MATRICE
    || ' '
    || V_RESULT.MEHA
    || ' '
    || V_RESULT.SUMNER_CRAKEHALL
    || ' '
    || V_RESULT.CAROLEI_WAYNWOOD
    || ' '
    || V_RESULT.HARROLD_WESTERLING
    || ' '
    || V_RESULT.MARON_BOTLEY
    || ' '
    || V_RESULT.CREATE_TIME
    || ' '
    || V_RESULT.UPDATE_TIME
    || ' '
    || V_RESULT.MERLYN_OF_PEBBLETON_ID
    || ' '
    || V_RESULT.AMBROSE_ID );
  RETURN V_RESULT.ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN NULL;
END;
END PKG_JUSTMAN;
CREATE SEQUENCE SEQ_MERLYN_OF_PEBBLETON INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AMBROSE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_OSGREY_OF_LEAFY_LAKE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_NYMEROS_MARTELL_OF_SUNSPEAR INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_JUSTMAN INCREMENT BY 1 START WITH 1;