name: Lint rolldebee/api

on:
  pull_request:
    branches:
      - main
    paths:
      - "api/**"
      - "!api/README.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: musichin/ktlint-check@v3
        with:
          ktlint-version: '1.4.0'
    permissions:
      contents: read
      pull-requests: read
      checks: write